// Generated by scripts/build-edge-function.mjs — DO NOT EDIT
// This file is auto-generated for Supabase Edge Function deployment.


// supabase/functions/generate-program/index.ts
import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.110.5";

// packages/program-engine/src/contracts.ts
var PROGRAM_ENGINE_VERSION = "program-engine-v1.2.0";
var PROGRAM_RULE_SET_VERSION = "program-rules-v1.2.0";

// packages/program-engine/src/generation.ts
var DAY_PATTERNS = {
  2: [1, 4],
  3: [1, 3, 5],
  4: [1, 2, 4, 6],
  5: [1, 2, 3, 5, 6],
  6: [1, 2, 3, 4, 5, 6]
};
var SPLITS = {
  2: [
    { name: "Full Body A", patterns: ["squat", "horizontal-press", "horizontal-pull", "hinge"] },
    { name: "Full Body B", patterns: ["hinge", "vertical-press", "vertical-pull", "single-leg"] }
  ],
  3: [
    { name: "Full Body A", patterns: ["squat", "horizontal-press", "horizontal-pull"] },
    { name: "Full Body B", patterns: ["hinge", "vertical-press", "vertical-pull"] },
    { name: "Full Body C", patterns: ["single-leg", "incline-press", "horizontal-pull"] }
  ],
  4: [
    { name: "Upper A", patterns: ["horizontal-press", "horizontal-pull", "vertical-press"] },
    { name: "Lower A", patterns: ["squat", "hinge", "calf-raise"] },
    { name: "Upper B", patterns: ["incline-press", "vertical-pull", "horizontal-pull"] },
    { name: "Lower B", patterns: ["single-leg", "hinge", "knee-flexion"] }
  ],
  5: [
    { name: "Upper", patterns: ["horizontal-press", "horizontal-pull", "vertical-press"] },
    { name: "Lower", patterns: ["squat", "hinge", "calf-raise"] },
    { name: "Push", patterns: ["incline-press", "vertical-press", "triceps-extension"] },
    { name: "Pull", patterns: ["vertical-pull", "horizontal-pull", "elbow-flexion"] },
    { name: "Legs", patterns: ["single-leg", "knee-extension", "knee-flexion"] }
  ],
  6: [
    { name: "Push A", patterns: ["horizontal-press", "vertical-press", "triceps-extension"] },
    { name: "Pull A", patterns: ["vertical-pull", "horizontal-pull", "elbow-flexion"] },
    { name: "Legs A", patterns: ["squat", "hinge", "calf-raise"] },
    { name: "Push B", patterns: ["incline-press", "vertical-press", "triceps-extension"] },
    { name: "Pull B", patterns: ["horizontal-pull", "vertical-pull", "elbow-flexion"] },
    { name: "Legs B", patterns: ["single-leg", "knee-extension", "knee-flexion"] }
  ]
};
function generateProgram(setup, catalog) {
  validateSetup(setup);
  const frequency = Math.min(6, Math.max(2, setup.daysPerWeek));
  const splitRows = SPLITS[frequency];
  const usable = catalog.filter((item) => !setup.dislikedExerciseIds.includes(item.id)).filter((item) => !setup.restrictedMovementPatterns.includes(item.movementPattern)).filter(
    (item) => item.equipment.length === 0 || item.equipment.some((e) => setup.equipment.includes(e))
  ).sort((a, b) => a.id.localeCompare(b.id));
  if (usable.length === 0)
    throw new Error("No exercises match the selected equipment and restrictions.");
  const templates = splitRows.map((row, index) => buildTemplate(row, index, setup, usable));
  const schedule = buildSchedule(setup, templates);
  return {
    name: `${goalName(setup.goal)} \xB7 ${setup.durationWeeks} weeks`,
    split: splitName(frequency, setup.programPreference),
    engineVersion: PROGRAM_ENGINE_VERSION,
    ruleSetVersion: PROGRAM_RULE_SET_VERSION,
    templates,
    schedule
  };
}
function buildTemplate(row, templateIndex, setup, catalog) {
  const maxExercises = setup.sessionDurationMinutes <= 45 ? 4 : setup.sessionDurationMinutes <= 75 ? 5 : 6;
  const selected = [];
  for (const pattern of row.patterns) {
    const match = catalog.find(
      (item) => item.movementPattern === pattern && !selected.includes(item)
    );
    if (match) selected.push(match);
  }
  for (const candidate of catalog) {
    if (selected.length >= maxExercises) break;
    if (!selected.includes(candidate)) selected.push(candidate);
  }
  const prescriptions = selected.slice(0, maxExercises).map((exercise, i) => prescription(exercise, i + 1, setup.goal, setup.experience));
  return {
    templateKey: `template-${templateIndex + 1}`,
    name: row.name,
    focus: [...new Set(prescriptions.map((item) => item.movementPattern))],
    expectedDurationMinutes: setup.sessionDurationMinutes,
    prescriptions
  };
}
function prescription(exercise, position, goal, experience) {
  const rules = goal === "gain_strength" ? { sets: experience === "beginner" ? 3 : 4, min: 3, max: 6, rir: 2, rest: 180 } : goal === "build_muscle" ? { sets: experience === "advanced" ? 4 : 3, min: 8, max: 12, rir: 2, rest: 120 } : goal === "fat_loss_support" ? { sets: 3, min: 10, max: 15, rir: 3, rest: 75 } : { sets: 3, min: 6, max: 12, rir: 2, rest: 105 };
  return {
    exerciseId: exercise.id,
    exerciseName: exercise.name,
    position,
    movementPattern: exercise.movementPattern,
    sets: rules.sets,
    repsMin: rules.min,
    repsMax: rules.max,
    targetRir: rules.rir,
    restSeconds: rules.rest,
    initialLoadKg: null,
    calibrationStatus: "calibration_required",
    recommendationReason: "Calibrate with a controlled set inside the prescribed rep and RIR range."
  };
}
function buildSchedule(setup, templates) {
  const start = parseDate(setup.startDate);
  const dayPattern = DAY_PATTERNS[Math.min(6, Math.max(2, setup.daysPerWeek))];
  const rows = [];
  for (let week = 1; week <= setup.durationWeeks; week += 1) {
    const deload = week % 4 === 0 && week !== setup.durationWeeks;
    const phase = deload ? "deload" : week <= 3 ? "foundation" : week > setup.durationWeeks * 0.75 ? "intensification" : "build";
    dayPattern.forEach((day, index) => {
      const date = new Date(start);
      date.setUTCDate(date.getUTCDate() + (week - 1) * 7 + day - 1);
      rows.push({
        scheduleKey: `week-${week}-session-${index + 1}`,
        week,
        dayOfWeek: day,
        scheduledDate: date.toISOString().slice(0, 10),
        phase,
        isDeload: deload,
        templateKey: templates[index % templates.length].templateKey
      });
    });
  }
  return rows;
}
function parseDate(value) {
  const parsed = /* @__PURE__ */ new Date(`${value}T00:00:00.000Z`);
  if (Number.isNaN(parsed.getTime())) throw new Error("Program start date is invalid.");
  return parsed;
}
function validateSetup(setup) {
  if (![8, 12, 16].includes(setup.durationWeeks))
    throw new Error("Program duration must be 8, 12, or 16 weeks.");
  if (setup.daysPerWeek < 2 || setup.daysPerWeek > 6)
    throw new Error("Training frequency must be between 2 and 6 days.");
}
function goalName(goal) {
  return {
    build_muscle: "Build muscle",
    gain_strength: "Strength",
    recomposition: "Recomposition",
    fat_loss_support: "Fat-loss support"
  }[goal];
}
function splitName(frequency, preference) {
  if (preference !== "app_decide")
    return { push_pull_legs: "Push Pull Legs", upper_lower: "Upper Lower", full_body: "Full Body" }[preference];
  if (frequency <= 3) return "Full Body";
  if (frequency === 4) return "Upper Lower";
  return "Push Pull Legs";
}

// supabase/functions/generate-program/index.ts
var corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS"
};
serve(async (request) => {
  if (request.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (request.method !== "POST")
    return json(
      { status: "error", code: "METHOD_NOT_ALLOWED", message: "Method not allowed." },
      405
    );
  try {
    const authorization = request.headers.get("Authorization");
    const token = authorization?.replace(/^Bearer\s+/i, "");
    if (!token)
      return json({ status: "error", code: "UNAUTHENTICATED", message: "Please sign in." }, 401);
    const url = Deno.env.get("SUPABASE_URL");
    const anonKey = Deno.env.get("SUPABASE_ANON_KEY");
    if (!url || !anonKey)
      return json(
        { status: "error", code: "SERVER_CONFIGURATION", message: "Server configuration error." },
        500
      );
    const client = createClient(url, anonKey, {
      auth: { persistSession: false },
      global: { headers: { Authorization: `Bearer ${token}` } }
    });
    const { data: userData, error: userError } = await client.auth.getUser(token);
    if (userError || !userData.user)
      return json({ status: "error", code: "UNAUTHENTICATED", message: "Session expired." }, 401);
    const setup = await request.json();
    const validation = validateSetup2(setup);
    if (validation)
      return json({ status: "error", code: "INVALID_REQUEST", message: validation }, 400);
    const [exercises, families, muscles, joins, equipment, equipmentJoins] = await Promise.all([
      client.from("exercises").select("id,name,exercise_family_id").eq("is_active", true).order("id"),
      client.from("exercise_families").select("id,slug"),
      client.from("muscles").select("id,slug"),
      client.from("exercise_muscles").select("exercise_id,muscle_id,role"),
      client.from("equipment").select("id,slug"),
      client.from("exercise_equipment").select("exercise_id,equipment_id,requirement")
    ]);
    const failed = [exercises, families, muscles, joins, equipment, equipmentJoins].find(
      (result) => result.error
    );
    if (failed?.error) throw new Error(failed.error.message);
    const familyMap = new Map(
      (families.data ?? []).map((row) => [String(row.id), String(row.slug)])
    );
    const muscleMap = new Map(
      (muscles.data ?? []).map((row) => [String(row.id), String(row.slug)])
    );
    const equipmentMap = new Map(
      (equipment.data ?? []).map((row) => [String(row.id), String(row.slug)])
    );
    const catalog = (exercises.data ?? []).map((row) => {
      const primary = (joins.data ?? []).find(
        (join) => join.exercise_id === row.id && join.role === "primary"
      );
      const required = (equipmentJoins.data ?? []).filter(
        (join) => join.exercise_id === row.id && join.requirement === "required"
      );
      return {
        id: String(row.id),
        name: String(row.name),
        movementPattern: familyMap.get(String(row.exercise_family_id)) ?? "other",
        primaryMuscle: muscleMap.get(String(primary?.muscle_id)) ?? "general",
        equipment: required.map((join) => equipmentMap.get(String(join.equipment_id)) ?? "").filter(Boolean)
      };
    });
    return json({ status: "success", program: generateProgram(setup, catalog) }, 200);
  } catch (error) {
    console.error(
      JSON.stringify({
        event: "program_generation_failed",
        message: error instanceof Error ? error.message : "unknown"
      })
    );
    return json(
      {
        status: "error",
        code: "GENERATION_FAILED",
        message: "We could not create your program. Please review your choices and try again."
      },
      500
    );
  }
});
function validateSetup2(value) {
  if (!value || !["build_muscle", "gain_strength", "recomposition", "fat_loss_support"].includes(value.goal))
    return "Choose a supported training goal.";
  if (![8, 12, 16].includes(value.durationWeeks)) return "Choose an 8, 12, or 16 week program.";
  if (!Number.isInteger(value.daysPerWeek) || value.daysPerWeek < 2 || value.daysPerWeek > 6)
    return "Choose between 2 and 6 training days.";
  return null;
}
function json(body, status) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" }
  });
}
