import {
  type ExerciseCatalogImport,
  type ExerciseImportRecord,
  type ExerciseSubstitutionImportRecord,
} from './exercise-catalog.js';
import {
  prepareExerciseCatalogImport,
  renderExerciseCatalogSeedSql,
  summarizeExerciseCatalogImport,
} from './exercise-catalog-importer.js';
import { parseVersionIdentifier } from './versions.js';

const versionResult = parseVersionIdentifier('exercise-catalog-v1', 'contract');

if (!versionResult.ok) {
  throw new Error('The production exercise catalog contract version must be valid.');
}

const chestExercises = [
  exercise(
    'barbell-bench-press',
    'Barbell Bench Press',
    'horizontal-press',
    'chest',
    ['barbell', 'bench'],
    ['flat bench press'],
    [
      ['triceps', 0.5],
      ['front-delts', 0.4],
    ],
  ),
  exercise(
    'dumbbell-bench-press',
    'Dumbbell Bench Press',
    'horizontal-press',
    'chest',
    ['dumbbell', 'bench'],
    ['flat dumbbell press'],
    [
      ['triceps', 0.4],
      ['front-delts', 0.4],
    ],
  ),
  exercise(
    'smith-bench-press',
    'Smith Machine Bench Press',
    'horizontal-press',
    'chest',
    ['smith-machine', 'bench'],
    ['smith flat press'],
    [
      ['triceps', 0.5],
      ['front-delts', 0.4],
    ],
  ),
  exercise(
    'selectorized-chest-press',
    'Selectorized Chest Press',
    'horizontal-press',
    'chest',
    ['selectorized-machine'],
    ['seated chest press'],
    [
      ['triceps', 0.4],
      ['front-delts', 0.3],
    ],
  ),
  exercise(
    'plate-loaded-chest-press',
    'Plate-Loaded Chest Press',
    'horizontal-press',
    'chest',
    ['plate-loaded-machine'],
    ['hammer-style chest press'],
    [
      ['triceps', 0.4],
      ['front-delts', 0.3],
    ],
  ),
  exercise(
    'push-up',
    'Push-Up',
    'horizontal-press',
    'chest',
    ['bodyweight'],
    ['press-up'],
    [
      ['triceps', 0.5],
      ['front-delts', 0.3],
    ],
  ),
  exercise(
    'chest-dip',
    'Chest-Focused Dip',
    'horizontal-press',
    'chest',
    ['bodyweight', 'dip-station'],
    ['forward-lean dip'],
    [
      ['triceps', 0.5],
      ['front-delts', 0.3],
    ],
  ),
  exercise(
    'incline-barbell-bench-press',
    'Incline Barbell Bench Press',
    'incline-press',
    'chest',
    ['barbell', 'bench'],
    ['incline bench press'],
    [
      ['front-delts', 0.6],
      ['triceps', 0.4],
    ],
  ),
  exercise(
    'incline-dumbbell-bench-press',
    'Incline Dumbbell Bench Press',
    'incline-press',
    'chest',
    ['dumbbell', 'bench'],
    ['incline dumbbell press'],
    [
      ['front-delts', 0.6],
      ['triceps', 0.4],
    ],
  ),
  exercise(
    'incline-smith-bench-press',
    'Incline Smith Machine Bench Press',
    'incline-press',
    'chest',
    ['smith-machine', 'bench'],
    ['smith incline press'],
    [
      ['front-delts', 0.6],
      ['triceps', 0.4],
    ],
  ),
  exercise(
    'incline-machine-chest-press',
    'Incline Machine Chest Press',
    'incline-press',
    'chest',
    ['plate-loaded-machine'],
    ['plate-loaded incline press'],
    [
      ['front-delts', 0.5],
      ['triceps', 0.4],
    ],
  ),
  exercise(
    'standing-cable-chest-press',
    'Standing Cable Chest Press',
    'horizontal-press',
    'chest',
    ['cable'],
    ['cable press'],
    [
      ['triceps', 0.4],
      ['front-delts', 0.3],
    ],
  ),
  exercise(
    'cable-chest-fly',
    'Cable Chest Fly',
    'chest-isolation',
    'chest',
    ['cable'],
    ['cable crossover'],
  ),
  exercise(
    'pec-deck-fly',
    'Pec Deck Fly',
    'chest-isolation',
    'chest',
    ['selectorized-machine'],
    ['machine chest fly'],
  ),
  exercise(
    'dumbbell-chest-fly',
    'Dumbbell Chest Fly',
    'chest-isolation',
    'chest',
    ['dumbbell', 'bench'],
    ['flat dumbbell fly'],
  ),
  exercise(
    'single-arm-cable-chest-press',
    'Single-Arm Cable Chest Press',
    'horizontal-press',
    'chest',
    ['cable'],
    ['unilateral cable press'],
    [
      ['triceps', 0.4],
      ['front-delts', 0.3],
    ],
  ),
] as const;

const backExercises = [
  exercise(
    'pull-up',
    'Pull-Up',
    'vertical-pull',
    'lats',
    ['bodyweight', 'pull-up-station'],
    ['bodyweight pull-up'],
    [
      ['biceps', 0.5],
      ['upper-back', 0.4],
    ],
  ),
  exercise(
    'assisted-pull-up',
    'Assisted Pull-Up',
    'vertical-pull',
    'lats',
    ['selectorized-machine', 'pull-up-station'],
    ['assisted chin station pull-up'],
    [
      ['biceps', 0.5],
      ['upper-back', 0.4],
    ],
  ),
  exercise(
    'lat-pulldown',
    'Lat Pulldown',
    'vertical-pull',
    'lats',
    ['cable'],
    ['cable pulldown'],
    [
      ['biceps', 0.5],
      ['upper-back', 0.4],
    ],
  ),
  exercise(
    'single-arm-lat-pulldown',
    'Single-Arm Lat Pulldown',
    'vertical-pull',
    'lats',
    ['cable'],
    ['unilateral pulldown'],
    [['biceps', 0.4]],
  ),
  exercise(
    'plate-loaded-lat-pulldown',
    'Plate-Loaded Lat Pulldown',
    'vertical-pull',
    'lats',
    ['plate-loaded-machine'],
    ['iso-lateral pulldown'],
    [
      ['biceps', 0.5],
      ['upper-back', 0.4],
    ],
  ),
  exercise(
    'dumbbell-pullover',
    'Dumbbell Pullover',
    'shoulder-extension',
    'lats',
    ['dumbbell', 'bench'],
    ['db pullover'],
    [['chest', 0.3]],
  ),
  exercise(
    'cable-pullover',
    'Cable Pullover',
    'shoulder-extension',
    'lats',
    ['cable'],
    ['straight-arm cable pulldown'],
  ),
  exercise(
    'barbell-bent-over-row',
    'Barbell Bent-Over Row',
    'horizontal-pull',
    'upper-back',
    ['barbell'],
    ['barbell row'],
    [
      ['lats', 0.7],
      ['biceps', 0.4],
      ['spinal-erectors', 0.4],
    ],
  ),
  exercise(
    'one-arm-dumbbell-row',
    'One-Arm Dumbbell Row',
    'horizontal-pull',
    'lats',
    ['dumbbell', 'bench'],
    ['single-arm dumbbell row'],
    [
      ['upper-back', 0.6],
      ['biceps', 0.4],
    ],
  ),
  exercise(
    'chest-supported-dumbbell-row',
    'Chest-Supported Dumbbell Row',
    'horizontal-pull',
    'upper-back',
    ['dumbbell', 'bench'],
    ['incline bench dumbbell row'],
    [
      ['lats', 0.6],
      ['biceps', 0.4],
    ],
  ),
  exercise(
    'seated-cable-row',
    'Seated Cable Row',
    'horizontal-pull',
    'upper-back',
    ['cable'],
    ['low cable row'],
    [
      ['lats', 0.7],
      ['biceps', 0.4],
    ],
  ),
  exercise(
    'selectorized-seated-row',
    'Selectorized Seated Row',
    'horizontal-pull',
    'upper-back',
    ['selectorized-machine'],
    ['machine seated row'],
    [
      ['lats', 0.7],
      ['biceps', 0.4],
    ],
  ),
  exercise(
    'plate-loaded-row',
    'Plate-Loaded Row',
    'horizontal-pull',
    'upper-back',
    ['plate-loaded-machine'],
    ['iso-lateral row'],
    [
      ['lats', 0.7],
      ['biceps', 0.4],
    ],
  ),
  exercise(
    'smith-bent-over-row',
    'Smith Machine Bent-Over Row',
    'horizontal-pull',
    'upper-back',
    ['smith-machine'],
    ['smith row'],
    [
      ['lats', 0.7],
      ['biceps', 0.4],
      ['spinal-erectors', 0.3],
    ],
  ),
  exercise(
    'inverted-row',
    'Inverted Row',
    'horizontal-pull',
    'upper-back',
    ['bodyweight', 'smith-machine'],
    ['body row'],
    [
      ['lats', 0.6],
      ['biceps', 0.4],
    ],
  ),
  exercise(
    'single-arm-cable-row',
    'Single-Arm Cable Row',
    'horizontal-pull',
    'lats',
    ['cable'],
    ['unilateral cable row'],
    [
      ['upper-back', 0.6],
      ['biceps', 0.4],
    ],
  ),
  exercise(
    'plate-loaded-t-bar-row',
    'Plate-Loaded T-Bar Row',
    'horizontal-pull',
    'upper-back',
    ['plate-loaded-machine'],
    ['chest-supported t-bar row'],
    [
      ['lats', 0.7],
      ['biceps', 0.4],
    ],
  ),
  exercise(
    'wide-grip-machine-row',
    'Wide-Grip Machine Row',
    'horizontal-pull',
    'upper-back',
    ['selectorized-machine'],
    ['upper-back row machine'],
    [
      ['rear-delts', 0.5],
      ['biceps', 0.3],
    ],
  ),
  exercise(
    'barbell-shrug',
    'Barbell Shrug',
    'scapular-elevation',
    'traps',
    ['barbell'],
    ['barbell shoulder shrug'],
    [['forearms', 0.3]],
  ),
  exercise(
    'dumbbell-shrug',
    'Dumbbell Shrug',
    'scapular-elevation',
    'traps',
    ['dumbbell'],
    ['db shrug'],
    [['forearms', 0.3]],
  ),
  exercise(
    'smith-machine-shrug',
    'Smith Machine Shrug',
    'scapular-elevation',
    'traps',
    ['smith-machine'],
    ['smith shrug'],
    [['forearms', 0.2]],
  ),
  exercise(
    'cable-shrug',
    'Cable Shrug',
    'scapular-elevation',
    'traps',
    ['cable'],
    ['low cable shrug'],
    [['forearms', 0.2]],
  ),
  exercise(
    'selectorized-pullover',
    'Selectorized Pullover',
    'shoulder-extension',
    'lats',
    ['selectorized-machine'],
    ['pullover machine'],
  ),
  exercise(
    'chest-supported-plate-loaded-row',
    'Chest-Supported Plate-Loaded Row',
    'horizontal-pull',
    'upper-back',
    ['plate-loaded-machine'],
    ['supported plate row'],
    [
      ['lats', 0.7],
      ['biceps', 0.4],
    ],
  ),
] as const;

const shoulderExercises = [
  exercise(
    'barbell-overhead-press',
    'Barbell Overhead Press',
    'vertical-press',
    'front-delts',
    ['barbell'],
    ['standing military press'],
    [
      ['side-delts', 0.6],
      ['triceps', 0.5],
    ],
  ),
  exercise(
    'standing-dumbbell-shoulder-press',
    'Standing Dumbbell Shoulder Press',
    'vertical-press',
    'front-delts',
    ['dumbbell'],
    ['standing db press'],
    [
      ['side-delts', 0.6],
      ['triceps', 0.5],
    ],
  ),
  exercise(
    'seated-dumbbell-shoulder-press',
    'Seated Dumbbell Shoulder Press',
    'vertical-press',
    'front-delts',
    ['dumbbell', 'bench'],
    ['seated db press'],
    [
      ['side-delts', 0.6],
      ['triceps', 0.5],
    ],
  ),
  exercise(
    'smith-machine-overhead-press',
    'Smith Machine Overhead Press',
    'vertical-press',
    'front-delts',
    ['smith-machine', 'bench'],
    ['smith shoulder press'],
    [
      ['side-delts', 0.6],
      ['triceps', 0.5],
    ],
  ),
  exercise(
    'selectorized-shoulder-press',
    'Selectorized Shoulder Press',
    'vertical-press',
    'front-delts',
    ['selectorized-machine'],
    ['machine shoulder press'],
    [
      ['side-delts', 0.6],
      ['triceps', 0.5],
    ],
  ),
  exercise(
    'plate-loaded-shoulder-press',
    'Plate-Loaded Shoulder Press',
    'vertical-press',
    'front-delts',
    ['plate-loaded-machine'],
    ['plate shoulder press'],
    [
      ['side-delts', 0.6],
      ['triceps', 0.5],
    ],
  ),
  exercise(
    'landmine-press',
    'Landmine Press',
    'vertical-press',
    'front-delts',
    ['barbell'],
    ['angled barbell press'],
    [
      ['chest', 0.4],
      ['triceps', 0.4],
    ],
  ),
  exercise(
    'single-arm-cable-shoulder-press',
    'Single-Arm Cable Shoulder Press',
    'vertical-press',
    'front-delts',
    ['cable'],
    ['unilateral cable overhead press'],
    [
      ['side-delts', 0.5],
      ['triceps', 0.4],
    ],
  ),
  exercise(
    'dumbbell-lateral-raise',
    'Dumbbell Lateral Raise',
    'shoulder-abduction',
    'side-delts',
    ['dumbbell'],
    ['db side raise'],
  ),
  exercise(
    'cable-lateral-raise',
    'Cable Lateral Raise',
    'shoulder-abduction',
    'side-delts',
    ['cable'],
    ['single-arm cable lateral raise'],
  ),
  exercise(
    'selectorized-lateral-raise',
    'Selectorized Lateral Raise',
    'shoulder-abduction',
    'side-delts',
    ['selectorized-machine'],
    ['lateral raise machine'],
  ),
  exercise(
    'leaning-cable-lateral-raise',
    'Leaning Cable Lateral Raise',
    'shoulder-abduction',
    'side-delts',
    ['cable'],
    ['behind-body cable lateral raise'],
  ),
  exercise(
    'reverse-pec-deck',
    'Reverse Pec Deck',
    'rear-delt',
    'rear-delts',
    ['selectorized-machine'],
    ['reverse fly machine'],
    [['upper-back', 0.4]],
  ),
  exercise(
    'cable-rear-delt-fly',
    'Cable Rear-Delt Fly',
    'rear-delt',
    'rear-delts',
    ['cable'],
    ['cable reverse fly'],
    [['upper-back', 0.4]],
  ),
  exercise(
    'bent-over-dumbbell-rear-delt-raise',
    'Bent-Over Dumbbell Rear-Delt Raise',
    'rear-delt',
    'rear-delts',
    ['dumbbell'],
    ['bent-over reverse fly'],
    [['upper-back', 0.4]],
  ),
  exercise(
    'cable-face-pull',
    'Cable Face Pull',
    'rear-delt',
    'rear-delts',
    ['cable'],
    ['rope face pull'],
    [
      ['upper-back', 0.5],
      ['traps', 0.3],
    ],
  ),
  exercise(
    'dumbbell-front-raise',
    'Dumbbell Front Raise',
    'shoulder-flexion',
    'front-delts',
    ['dumbbell'],
    ['db front raise'],
  ),
  exercise(
    'cable-front-raise',
    'Cable Front Raise',
    'shoulder-flexion',
    'front-delts',
    ['cable'],
    ['low cable front raise'],
  ),
] as const;

const armExercises = [
  exercise(
    'barbell-curl',
    'Barbell Curl',
    'elbow-flexion',
    'biceps',
    ['barbell'],
    ['straight-bar curl'],
    [['forearms', 0.3]],
  ),
  exercise(
    'alternating-dumbbell-curl',
    'Alternating Dumbbell Curl',
    'elbow-flexion',
    'biceps',
    ['dumbbell'],
    ['alternating db curl'],
    [['forearms', 0.3]],
  ),
  exercise(
    'incline-dumbbell-curl',
    'Incline Dumbbell Curl',
    'elbow-flexion',
    'biceps',
    ['dumbbell', 'bench'],
    ['incline curl'],
  ),
  exercise(
    'dumbbell-hammer-curl',
    'Dumbbell Hammer Curl',
    'elbow-flexion',
    'biceps',
    ['dumbbell'],
    ['neutral-grip curl'],
    [['forearms', 0.5]],
  ),
  exercise(
    'barbell-preacher-curl',
    'Barbell Preacher Curl',
    'elbow-flexion',
    'biceps',
    ['barbell', 'bench'],
    ['preacher bar curl'],
  ),
  exercise(
    'single-arm-dumbbell-preacher-curl',
    'Single-Arm Dumbbell Preacher Curl',
    'elbow-flexion',
    'biceps',
    ['dumbbell', 'bench'],
    ['unilateral preacher curl'],
  ),
  exercise(
    'selectorized-preacher-curl',
    'Selectorized Preacher Curl',
    'elbow-flexion',
    'biceps',
    ['selectorized-machine'],
    ['machine preacher curl'],
  ),
  exercise(
    'standing-cable-curl',
    'Standing Cable Curl',
    'elbow-flexion',
    'biceps',
    ['cable'],
    ['low cable curl'],
  ),
  exercise(
    'bayesian-cable-curl',
    'Bayesian Cable Curl',
    'elbow-flexion',
    'biceps',
    ['cable'],
    ['behind-body cable curl'],
  ),
  exercise(
    'dumbbell-concentration-curl',
    'Dumbbell Concentration Curl',
    'elbow-flexion',
    'biceps',
    ['dumbbell'],
    ['concentration curl'],
  ),
  exercise(
    'barbell-reverse-curl',
    'Barbell Reverse Curl',
    'elbow-flexion',
    'forearms',
    ['barbell'],
    ['pronated barbell curl'],
    [['biceps', 0.5]],
  ),
  exercise(
    'rope-hammer-curl',
    'Rope Hammer Curl',
    'elbow-flexion',
    'biceps',
    ['cable'],
    ['cable rope curl'],
    [['forearms', 0.5]],
  ),
  exercise(
    'dumbbell-wrist-curl',
    'Dumbbell Wrist Curl',
    'wrist-flexion',
    'forearms',
    ['dumbbell', 'bench'],
    ['seated wrist curl'],
  ),
  exercise(
    'dumbbell-reverse-wrist-curl',
    'Dumbbell Reverse Wrist Curl',
    'wrist-extension',
    'forearms',
    ['dumbbell', 'bench'],
    ['wrist extension curl'],
  ),
  exercise(
    'dumbbell-farmer-carry',
    'Dumbbell Farmer Carry',
    'loaded-carry',
    'forearms',
    ['dumbbell'],
    ['farmer walk'],
    [
      ['traps', 0.6],
      ['abs', 0.4],
    ],
  ),
  exercise(
    'cable-reverse-curl',
    'Cable Reverse Curl',
    'elbow-flexion',
    'forearms',
    ['cable'],
    ['pronated cable curl'],
    [['biceps', 0.5]],
  ),
  exercise(
    'cable-triceps-pushdown',
    'Cable Triceps Pushdown',
    'elbow-extension',
    'triceps',
    ['cable'],
    ['triceps pressdown'],
  ),
  exercise(
    'single-arm-cable-pushdown',
    'Single-Arm Cable Pushdown',
    'elbow-extension',
    'triceps',
    ['cable'],
    ['unilateral pressdown'],
  ),
  exercise(
    'overhead-cable-triceps-extension',
    'Overhead Cable Triceps Extension',
    'elbow-extension',
    'triceps',
    ['cable'],
    ['cable overhead extension'],
  ),
  exercise(
    'dumbbell-overhead-triceps-extension',
    'Dumbbell Overhead Triceps Extension',
    'elbow-extension',
    'triceps',
    ['dumbbell'],
    ['overhead dumbbell extension'],
  ),
  exercise(
    'lying-barbell-triceps-extension',
    'Lying Barbell Triceps Extension',
    'elbow-extension',
    'triceps',
    ['barbell', 'bench'],
    ['barbell skull crusher'],
  ),
  exercise(
    'lying-dumbbell-triceps-extension',
    'Lying Dumbbell Triceps Extension',
    'elbow-extension',
    'triceps',
    ['dumbbell', 'bench'],
    ['dumbbell skull crusher'],
  ),
  exercise(
    'close-grip-barbell-bench-press',
    'Close-Grip Barbell Bench Press',
    'elbow-extension',
    'triceps',
    ['barbell', 'bench'],
    ['close-grip bench'],
    [
      ['chest', 0.6],
      ['front-delts', 0.3],
    ],
  ),
  exercise(
    'triceps-dip',
    'Triceps-Focused Dip',
    'elbow-extension',
    'triceps',
    ['bodyweight', 'dip-station'],
    ['upright dip'],
    [
      ['chest', 0.5],
      ['front-delts', 0.3],
    ],
  ),
  exercise(
    'selectorized-triceps-extension',
    'Selectorized Triceps Extension',
    'elbow-extension',
    'triceps',
    ['selectorized-machine'],
    ['triceps extension machine'],
  ),
  exercise(
    'cross-body-cable-triceps-extension',
    'Cross-Body Cable Triceps Extension',
    'elbow-extension',
    'triceps',
    ['cable'],
    ['cross-cable extension'],
  ),
  exercise(
    'dumbbell-triceps-kickback',
    'Dumbbell Triceps Kickback',
    'elbow-extension',
    'triceps',
    ['dumbbell'],
    ['db kickback'],
  ),
  exercise(
    'smith-jm-press',
    'Smith Machine JM Press',
    'elbow-extension',
    'triceps',
    ['smith-machine', 'bench'],
    ['smith triceps press'],
    [
      ['chest', 0.4],
      ['front-delts', 0.3],
    ],
  ),
] as const;

const lowerBodyExercises = [
  exercise(
    'barbell-back-squat',
    'Barbell Back Squat',
    'knee-dominant-squat',
    'quadriceps',
    ['barbell'],
    ['back squat'],
    [
      ['glutes', 0.7],
      ['adductors', 0.4],
      ['spinal-erectors', 0.3],
    ],
  ),
  exercise(
    'barbell-front-squat',
    'Barbell Front Squat',
    'knee-dominant-squat',
    'quadriceps',
    ['barbell'],
    ['front squat'],
    [
      ['glutes', 0.5],
      ['abs', 0.4],
    ],
  ),
  exercise(
    'smith-machine-squat',
    'Smith Machine Squat',
    'knee-dominant-squat',
    'quadriceps',
    ['smith-machine'],
    ['smith squat'],
    [['glutes', 0.6]],
  ),
  exercise(
    'dumbbell-goblet-squat',
    'Dumbbell Goblet Squat',
    'knee-dominant-squat',
    'quadriceps',
    ['dumbbell'],
    ['goblet squat'],
    [
      ['glutes', 0.6],
      ['abs', 0.3],
    ],
  ),
  exercise(
    'dumbbell-bulgarian-split-squat',
    'Dumbbell Bulgarian Split Squat',
    'unilateral-knee-dominant',
    'quadriceps',
    ['dumbbell', 'bench'],
    ['rear-foot-elevated split squat'],
    [
      ['glutes', 0.7],
      ['adductors', 0.3],
    ],
  ),
  exercise(
    'dumbbell-walking-lunge',
    'Dumbbell Walking Lunge',
    'unilateral-knee-dominant',
    'quadriceps',
    ['dumbbell'],
    ['walking lunge'],
    [
      ['glutes', 0.7],
      ['adductors', 0.3],
    ],
  ),
  exercise(
    'dumbbell-reverse-lunge',
    'Dumbbell Reverse Lunge',
    'unilateral-knee-dominant',
    'glutes',
    ['dumbbell'],
    ['reverse lunge'],
    [
      ['quadriceps', 0.7],
      ['adductors', 0.3],
    ],
  ),
  exercise(
    'dumbbell-step-up',
    'Dumbbell Step-Up',
    'unilateral-knee-dominant',
    'glutes',
    ['dumbbell', 'bench'],
    ['weighted step-up'],
    [['quadriceps', 0.7]],
  ),
  exercise(
    'leg-press',
    'Leg Press',
    'knee-dominant-squat',
    'quadriceps',
    ['leg-press'],
    ['sled leg press'],
    [
      ['glutes', 0.6],
      ['adductors', 0.3],
    ],
  ),
  exercise(
    'hack-squat',
    'Hack Squat',
    'knee-dominant-squat',
    'quadriceps',
    ['hack-squat'],
    ['hack squat machine'],
    [['glutes', 0.5]],
  ),
  exercise(
    'smith-machine-split-squat',
    'Smith Machine Split Squat',
    'unilateral-knee-dominant',
    'quadriceps',
    ['smith-machine'],
    ['smith split squat'],
    [['glutes', 0.7]],
  ),
  exercise(
    'plate-loaded-pendulum-squat',
    'Plate-Loaded Pendulum Squat',
    'knee-dominant-squat',
    'quadriceps',
    ['plate-loaded-machine'],
    ['pendulum squat'],
    [['glutes', 0.5]],
  ),
  exercise(
    'selectorized-leg-extension',
    'Selectorized Leg Extension',
    'knee-extension',
    'quadriceps',
    ['selectorized-machine'],
    ['machine leg extension'],
  ),
  exercise(
    'single-leg-extension',
    'Single-Leg Extension',
    'knee-extension',
    'quadriceps',
    ['selectorized-machine'],
    ['unilateral leg extension'],
  ),
  exercise(
    'cable-leg-extension',
    'Cable Leg Extension',
    'knee-extension',
    'quadriceps',
    ['cable'],
    ['ankle-strap leg extension'],
  ),
  exercise(
    'barbell-romanian-deadlift',
    'Barbell Romanian Deadlift',
    'hip-hinge',
    'hamstrings',
    ['barbell'],
    ['barbell rdl'],
    [
      ['glutes', 0.8],
      ['spinal-erectors', 0.4],
    ],
  ),
  exercise(
    'dumbbell-romanian-deadlift',
    'Dumbbell Romanian Deadlift',
    'hip-hinge',
    'hamstrings',
    ['dumbbell'],
    ['dumbbell rdl'],
    [
      ['glutes', 0.8],
      ['spinal-erectors', 0.3],
    ],
  ),
  exercise(
    'smith-machine-romanian-deadlift',
    'Smith Machine Romanian Deadlift',
    'hip-hinge',
    'hamstrings',
    ['smith-machine'],
    ['smith rdl'],
    [
      ['glutes', 0.8],
      ['spinal-erectors', 0.3],
    ],
  ),
  exercise(
    'conventional-barbell-deadlift',
    'Conventional Barbell Deadlift',
    'hip-hinge',
    'glutes',
    ['barbell'],
    ['conventional deadlift'],
    [
      ['hamstrings', 0.7],
      ['spinal-erectors', 0.6],
      ['traps', 0.3],
    ],
  ),
  exercise(
    'sumo-barbell-deadlift',
    'Sumo Barbell Deadlift',
    'hip-hinge',
    'glutes',
    ['barbell'],
    ['sumo deadlift'],
    [
      ['adductors', 0.7],
      ['quadriceps', 0.5],
      ['hamstrings', 0.4],
    ],
  ),
  exercise(
    'barbell-good-morning',
    'Barbell Good Morning',
    'hip-hinge',
    'hamstrings',
    ['barbell'],
    ['good morning'],
    [
      ['glutes', 0.7],
      ['spinal-erectors', 0.5],
    ],
  ),
  exercise(
    'selectorized-seated-leg-curl',
    'Selectorized Seated Leg Curl',
    'knee-flexion',
    'hamstrings',
    ['selectorized-machine'],
    ['seated hamstring curl'],
  ),
  exercise(
    'selectorized-lying-leg-curl',
    'Selectorized Lying Leg Curl',
    'knee-flexion',
    'hamstrings',
    ['selectorized-machine'],
    ['prone leg curl'],
  ),
  exercise(
    'single-leg-standing-curl',
    'Single-Leg Standing Curl',
    'knee-flexion',
    'hamstrings',
    ['selectorized-machine'],
    ['standing hamstring curl'],
  ),
  exercise(
    'cable-leg-curl',
    'Cable Leg Curl',
    'knee-flexion',
    'hamstrings',
    ['cable'],
    ['ankle-strap hamstring curl'],
  ),
  exercise(
    'nordic-hamstring-curl',
    'Nordic Hamstring Curl',
    'knee-flexion',
    'hamstrings',
    ['bodyweight', 'bench'],
    ['nordic curl'],
  ),
  exercise(
    'barbell-hip-thrust',
    'Barbell Hip Thrust',
    'hip-extension',
    'glutes',
    ['barbell', 'bench'],
    ['barbell glute thrust'],
    [['hamstrings', 0.4]],
  ),
  exercise(
    'smith-machine-hip-thrust',
    'Smith Machine Hip Thrust',
    'hip-extension',
    'glutes',
    ['smith-machine', 'bench'],
    ['smith hip thrust'],
    [['hamstrings', 0.4]],
  ),
  exercise(
    'dumbbell-hip-thrust',
    'Dumbbell Hip Thrust',
    'hip-extension',
    'glutes',
    ['dumbbell', 'bench'],
    ['db hip thrust'],
    [['hamstrings', 0.4]],
  ),
  exercise(
    'selectorized-glute-drive',
    'Selectorized Glute Drive',
    'hip-extension',
    'glutes',
    ['selectorized-machine'],
    ['glute drive machine'],
    [['hamstrings', 0.4]],
  ),
  exercise(
    'cable-pull-through',
    'Cable Pull-Through',
    'hip-extension',
    'glutes',
    ['cable'],
    ['rope pull-through'],
    [['hamstrings', 0.6]],
  ),
  exercise(
    'cable-glute-kickback',
    'Cable Glute Kickback',
    'hip-extension',
    'glutes',
    ['cable'],
    ['cable hip extension'],
  ),
  exercise(
    'selectorized-hip-abduction',
    'Selectorized Hip Abduction',
    'hip-abduction',
    'abductors',
    ['selectorized-machine'],
    ['hip abductor machine'],
    [['glutes', 0.4]],
  ),
  exercise(
    'standing-cable-hip-abduction',
    'Standing Cable Hip Abduction',
    'hip-abduction',
    'abductors',
    ['cable'],
    ['cable side leg raise'],
    [['glutes', 0.4]],
  ),
  exercise(
    'selectorized-hip-adduction',
    'Selectorized Hip Adduction',
    'hip-adduction',
    'adductors',
    ['selectorized-machine'],
    ['hip adductor machine'],
  ),
  exercise(
    'standing-cable-hip-adduction',
    'Standing Cable Hip Adduction',
    'hip-adduction',
    'adductors',
    ['cable'],
    ['cable inner-thigh pull'],
  ),
  exercise(
    'selectorized-standing-calf-raise',
    'Selectorized Standing Calf Raise',
    'calf-raise',
    'calves',
    ['selectorized-machine'],
    ['standing calf machine'],
  ),
  exercise(
    'plate-loaded-seated-calf-raise',
    'Plate-Loaded Seated Calf Raise',
    'calf-raise',
    'calves',
    ['plate-loaded-machine'],
    ['seated calf machine'],
  ),
  exercise(
    'leg-press-calf-raise',
    'Leg Press Calf Raise',
    'calf-raise',
    'calves',
    ['leg-press'],
    ['calf press'],
  ),
  exercise(
    'dumbbell-standing-calf-raise',
    'Dumbbell Standing Calf Raise',
    'calf-raise',
    'calves',
    ['dumbbell'],
    ['weighted standing calf raise'],
  ),
  exercise(
    'smith-machine-calf-raise',
    'Smith Machine Calf Raise',
    'calf-raise',
    'calves',
    ['smith-machine'],
    ['smith standing calf raise'],
  ),
  exercise(
    'back-extension',
    'Back Extension',
    'hip-hinge',
    'spinal-erectors',
    ['bodyweight', 'bench'],
    ['hyperextension'],
    [
      ['glutes', 0.6],
      ['hamstrings', 0.5],
    ],
  ),
] as const;

const coreExercises = [
  exercise(
    'kneeling-cable-crunch',
    'Kneeling Cable Crunch',
    'trunk-flexion',
    'abs',
    ['cable'],
    ['rope cable crunch'],
  ),
  exercise(
    'selectorized-abdominal-crunch',
    'Selectorized Abdominal Crunch',
    'trunk-flexion',
    'abs',
    ['selectorized-machine'],
    ['ab crunch machine'],
  ),
  exercise(
    'decline-bench-crunch',
    'Decline Bench Crunch',
    'trunk-flexion',
    'abs',
    ['bodyweight', 'bench'],
    ['decline sit-up'],
  ),
  exercise(
    'hanging-knee-raise',
    'Hanging Knee Raise',
    'hip-flexion-core',
    'abs',
    ['bodyweight', 'pull-up-station'],
    ['hanging knee tuck'],
  ),
  exercise(
    'hanging-leg-raise',
    'Hanging Leg Raise',
    'hip-flexion-core',
    'abs',
    ['bodyweight', 'pull-up-station'],
    ['straight-leg raise'],
  ),
  exercise(
    'ab-wheel-rollout',
    'Ab Wheel Rollout',
    'anti-extension',
    'abs',
    ['bodyweight'],
    ['kneeling rollout'],
  ),
  exercise('front-plank', 'Front Plank', 'anti-extension', 'abs', ['bodyweight'], ['prone plank']),
  exercise('dead-bug', 'Dead Bug', 'anti-extension', 'abs', ['bodyweight'], ['supine dead bug']),
  exercise(
    'cable-pallof-press',
    'Cable Pallof Press',
    'anti-rotation',
    'abs',
    ['cable'],
    ['anti-rotation cable press'],
  ),
  exercise(
    'cable-wood-chop',
    'Cable Wood Chop',
    'trunk-rotation',
    'abs',
    ['cable'],
    ['high-to-low cable chop'],
  ),
  exercise(
    'cable-lift',
    'Cable Lift',
    'trunk-rotation',
    'abs',
    ['cable'],
    ['low-to-high cable chop'],
  ),
  exercise('side-plank', 'Side Plank', 'lateral-core', 'abs', ['bodyweight'], ['lateral plank']),
] as const;

const substitutions = [
  substitution('barbell-bench-press', 'dumbbell-bench-press', 'barbell_unavailable', 0.92),
  substitution('barbell-bench-press', 'smith-bench-press', 'free_weight_station_unavailable', 0.9),
  substitution(
    'barbell-bench-press',
    'plate-loaded-chest-press',
    'bench_station_unavailable',
    0.84,
  ),
  substitution('dumbbell-bench-press', 'barbell-bench-press', 'dumbbells_unavailable', 0.9),
  substitution('dumbbell-bench-press', 'selectorized-chest-press', 'bench_unavailable', 0.82),
  substitution(
    'incline-barbell-bench-press',
    'incline-dumbbell-bench-press',
    'barbell_unavailable',
    0.92,
  ),
  substitution(
    'incline-barbell-bench-press',
    'incline-smith-bench-press',
    'free_weight_station_unavailable',
    0.9,
  ),
  substitution(
    'incline-dumbbell-bench-press',
    'incline-machine-chest-press',
    'bench_unavailable',
    0.84,
  ),
  substitution(
    'barbell-overhead-press',
    'standing-dumbbell-shoulder-press',
    'barbell_unavailable',
    0.9,
  ),
  substitution(
    'barbell-overhead-press',
    'smith-machine-overhead-press',
    'free_weight_station_unavailable',
    0.88,
  ),
  substitution(
    'seated-dumbbell-shoulder-press',
    'selectorized-shoulder-press',
    'dumbbells_unavailable',
    0.86,
  ),
  substitution(
    'smith-machine-overhead-press',
    'plate-loaded-shoulder-press',
    'smith_station_unavailable',
    0.84,
  ),
  substitution('lat-pulldown', 'pull-up', 'cable_station_unavailable', 0.86),
  substitution('lat-pulldown', 'plate-loaded-lat-pulldown', 'cable_station_unavailable', 0.9),
  substitution('pull-up', 'assisted-pull-up', 'assistance_required', 0.9),
  substitution('pull-up', 'lat-pulldown', 'pull_up_station_unavailable', 0.86),
  substitution('seated-cable-row', 'selectorized-seated-row', 'cable_station_unavailable', 0.9),
  substitution('seated-cable-row', 'plate-loaded-row', 'cable_station_unavailable', 0.86),
  substitution('barbell-bent-over-row', 'one-arm-dumbbell-row', 'barbell_unavailable', 0.85),
  substitution(
    'barbell-bent-over-row',
    'smith-bent-over-row',
    'free_weight_station_unavailable',
    0.9,
  ),
  substitution(
    'barbell-bent-over-row',
    'chest-supported-dumbbell-row',
    'supported_row_preferred',
    0.8,
  ),
  substitution('selectorized-seated-row', 'single-arm-cable-row', 'row_machine_unavailable', 0.82),
  substitution('barbell-back-squat', 'smith-machine-squat', 'rack_unavailable', 0.9),
  substitution('barbell-back-squat', 'dumbbell-goblet-squat', 'barbell_unavailable', 0.78),
  substitution('barbell-back-squat', 'leg-press', 'squat_station_unavailable', 0.76),
  substitution('leg-press', 'hack-squat', 'leg_press_unavailable', 0.88),
  substitution('leg-press', 'smith-machine-squat', 'leg_press_unavailable', 0.78),
  substitution('hack-squat', 'leg-press', 'hack_squat_unavailable', 0.88),
  substitution('hack-squat', 'plate-loaded-pendulum-squat', 'hack_squat_unavailable', 0.84),
  substitution(
    'barbell-romanian-deadlift',
    'dumbbell-romanian-deadlift',
    'barbell_unavailable',
    0.92,
  ),
  substitution(
    'barbell-romanian-deadlift',
    'smith-machine-romanian-deadlift',
    'free_weight_station_unavailable',
    0.9,
  ),
  substitution('dumbbell-romanian-deadlift', 'cable-pull-through', 'dumbbells_unavailable', 0.74),
  substitution(
    'barbell-hip-thrust',
    'smith-machine-hip-thrust',
    'barbell_station_unavailable',
    0.92,
  ),
  substitution('barbell-hip-thrust', 'dumbbell-hip-thrust', 'barbell_unavailable', 0.84),
  substitution(
    'smith-machine-hip-thrust',
    'selectorized-glute-drive',
    'smith_station_unavailable',
    0.88,
  ),
  substitution(
    'selectorized-leg-extension',
    'cable-leg-extension',
    'leg_extension_unavailable',
    0.78,
  ),
  substitution(
    'selectorized-leg-extension',
    'single-leg-extension',
    'bilateral_setup_unavailable',
    0.94,
  ),
  substitution(
    'selectorized-seated-leg-curl',
    'selectorized-lying-leg-curl',
    'seated_curl_unavailable',
    0.9,
  ),
  substitution(
    'selectorized-seated-leg-curl',
    'cable-leg-curl',
    'leg_curl_machine_unavailable',
    0.76,
  ),
  substitution('dumbbell-lateral-raise', 'cable-lateral-raise', 'dumbbells_unavailable', 0.9),
  substitution(
    'dumbbell-lateral-raise',
    'selectorized-lateral-raise',
    'free_weights_unavailable',
    0.86,
  ),
  substitution(
    'selectorized-lateral-raise',
    'cable-lateral-raise',
    'lateral_raise_machine_unavailable',
    0.9,
  ),
  substitution('barbell-curl', 'alternating-dumbbell-curl', 'barbell_unavailable', 0.88),
  substitution('barbell-curl', 'standing-cable-curl', 'free_weights_unavailable', 0.86),
  substitution(
    'selectorized-preacher-curl',
    'single-arm-dumbbell-preacher-curl',
    'curl_machine_unavailable',
    0.86,
  ),
  substitution(
    'cable-triceps-pushdown',
    'single-arm-cable-pushdown',
    'attachment_unavailable',
    0.92,
  ),
  substitution(
    'cable-triceps-pushdown',
    'selectorized-triceps-extension',
    'cable_station_unavailable',
    0.82,
  ),
  substitution(
    'overhead-cable-triceps-extension',
    'dumbbell-overhead-triceps-extension',
    'cable_station_unavailable',
    0.88,
  ),
  substitution('pec-deck-fly', 'cable-chest-fly', 'pec_deck_unavailable', 0.9),
  substitution('reverse-pec-deck', 'cable-rear-delt-fly', 'reverse_fly_machine_unavailable', 0.9),
] as const;

export const productionExerciseCatalog: ExerciseCatalogImport = {
  contractVersion: versionResult.value,
  payload: {
    muscles: [
      reference('chest', 'Chest'),
      reference('lats', 'Lats'),
      reference('upper-back', 'Upper Back'),
      reference('traps', 'Traps'),
      reference('front-delts', 'Front Delts'),
      reference('side-delts', 'Side Delts'),
      reference('rear-delts', 'Rear Delts'),
      reference('biceps', 'Biceps'),
      reference('triceps', 'Triceps'),
      reference('forearms', 'Forearms'),
      reference('quadriceps', 'Quadriceps'),
      reference('hamstrings', 'Hamstrings'),
      reference('glutes', 'Glutes'),
      reference('calves', 'Calves'),
      reference('abs', 'Abs'),
      reference('spinal-erectors', 'Spinal Erectors'),
      reference('adductors', 'Adductors'),
      reference('abductors', 'Abductors'),
    ],
    equipment: [
      reference('bodyweight', 'Bodyweight'),
      reference('barbell', 'Barbell'),
      reference('dumbbell', 'Dumbbell'),
      reference('cable', 'Cable'),
      reference('smith-machine', 'Smith Machine'),
      reference('selectorized-machine', 'Selectorized Machine'),
      reference('plate-loaded-machine', 'Plate-Loaded Machine'),
      reference('bench', 'Bench'),
      reference('pull-up-station', 'Pull-Up Station'),
      reference('dip-station', 'Dip Station'),
      reference('leg-press', 'Leg Press'),
      reference('hack-squat', 'Hack Squat'),
    ],
    exerciseFamilies: [
      reference('horizontal-press', 'Horizontal Press'),
      reference('incline-press', 'Incline Press'),
      reference('chest-isolation', 'Chest Isolation'),
      reference('vertical-pull', 'Vertical Pull'),
      reference('shoulder-extension', 'Shoulder Extension'),
      reference('horizontal-pull', 'Horizontal Pull'),
      reference('scapular-elevation', 'Scapular Elevation'),
      reference('vertical-press', 'Vertical Press'),
      reference('shoulder-abduction', 'Shoulder Abduction'),
      reference('rear-delt', 'Rear-Delt Work'),
      reference('shoulder-flexion', 'Shoulder Flexion'),
      reference('elbow-flexion', 'Elbow Flexion'),
      reference('wrist-flexion', 'Wrist Flexion'),
      reference('wrist-extension', 'Wrist Extension'),
      reference('loaded-carry', 'Loaded Carry'),
      reference('elbow-extension', 'Elbow Extension'),
      reference('knee-dominant-squat', 'Knee-Dominant Squat'),
      reference('unilateral-knee-dominant', 'Unilateral Knee-Dominant'),
      reference('knee-extension', 'Knee Extension'),
      reference('hip-hinge', 'Hip Hinge'),
      reference('knee-flexion', 'Knee Flexion'),
      reference('hip-extension', 'Hip Extension'),
      reference('hip-abduction', 'Hip Abduction'),
      reference('hip-adduction', 'Hip Adduction'),
      reference('calf-raise', 'Calf Raise'),
      reference('trunk-flexion', 'Trunk Flexion'),
      reference('hip-flexion-core', 'Hip Flexion Core'),
      reference('anti-extension', 'Anti-Extension'),
      reference('anti-rotation', 'Anti-Rotation'),
      reference('trunk-rotation', 'Trunk Rotation'),
      reference('lateral-core', 'Lateral Core'),
    ],
    exercises: [
      ...chestExercises,
      ...backExercises,
      ...shoulderExercises,
      ...armExercises,
      ...lowerBodyExercises,
      ...coreExercises,
    ],
    substitutions,
  },
};

const productionImportPlanResult = prepareExerciseCatalogImport(productionExerciseCatalog);

if (!productionImportPlanResult.ok) {
  throw new Error('The production exercise catalog must pass deterministic validation.');
}

export const productionExerciseCatalogImportPlan = productionImportPlanResult.value;
export const productionExerciseCatalogSeedSql = renderExerciseCatalogSeedSql(
  productionExerciseCatalogImportPlan,
);

export const productionExerciseCatalogStatistics = {
  ...summarizeExerciseCatalogImport(productionExerciseCatalog),
  exerciseFamilyCount: productionExerciseCatalog.payload.exerciseFamilies.length,
  exercisesByMajorArea: countExercisesByMajorArea(productionExerciseCatalog),
} as const;

function reference(slug: string, name: string) {
  return { slug, name, isActive: true } as const;
}

function exercise(
  slug: string,
  name: string,
  exerciseFamilySlug: string,
  primaryMuscleSlug: string,
  equipmentSlugs: readonly string[],
  aliases: readonly string[] = [],
  secondaryMuscles: readonly (readonly [muscleSlug: string, contribution: number])[] = [],
): ExerciseImportRecord {
  return {
    slug,
    name,
    aliases,
    exerciseFamilySlug,
    version: 1,
    isActive: true,
    muscles: [
      { muscleSlug: primaryMuscleSlug, role: 'primary', contribution: 1 },
      ...secondaryMuscles.map(([muscleSlug, contribution]) => ({
        muscleSlug,
        role: 'secondary' as const,
        contribution,
      })),
    ],
    equipment: equipmentSlugs.map((equipmentSlug) => ({
      equipmentSlug,
      requirement: 'required' as const,
    })),
  };
}

function substitution(
  sourceExerciseSlug: string,
  substituteExerciseSlug: string,
  reasonCode: string,
  compatibilityScore: number,
): ExerciseSubstitutionImportRecord {
  return {
    sourceExerciseSlug,
    substituteExerciseSlug,
    reasonCode,
    compatibilityScore,
    isActive: true,
  };
}

function countExercisesByMajorArea(
  catalog: ExerciseCatalogImport,
): Readonly<Record<string, number>> {
  const muscleArea = new Map<string, string>([
    ['chest', 'chest'],
    ['lats', 'back'],
    ['upper-back', 'back'],
    ['traps', 'back'],
    ['front-delts', 'shoulders'],
    ['side-delts', 'shoulders'],
    ['rear-delts', 'shoulders'],
    ['biceps', 'arms'],
    ['triceps', 'arms'],
    ['forearms', 'arms'],
    ['quadriceps', 'lower-body'],
    ['hamstrings', 'lower-body'],
    ['glutes', 'lower-body'],
    ['calves', 'lower-body'],
    ['spinal-erectors', 'lower-body'],
    ['adductors', 'lower-body'],
    ['abductors', 'lower-body'],
    ['abs', 'core'],
  ]);
  const counts: Record<string, number> = {};

  catalog.payload.exercises.forEach((catalogExercise) => {
    const primaryMuscle = catalogExercise.muscles.find(({ role }) => role === 'primary');
    const area = primaryMuscle ? muscleArea.get(primaryMuscle.muscleSlug) : undefined;

    if (area) {
      counts[area] = (counts[area] ?? 0) + 1;
    }
  });

  return counts;
}
