-- Generated from packages/domain/src/exercise-catalog-data.ts.
-- Regenerate through the deterministic exercise catalog importer; do not edit manually.

insert into public.muscles (slug, name, description, is_active)
values
  ('abductors', 'Abductors', null, true),
  ('abs', 'Abs', null, true),
  ('adductors', 'Adductors', null, true),
  ('biceps', 'Biceps', null, true),
  ('calves', 'Calves', null, true),
  ('chest', 'Chest', null, true),
  ('forearms', 'Forearms', null, true),
  ('front-delts', 'Front Delts', null, true),
  ('glutes', 'Glutes', null, true),
  ('hamstrings', 'Hamstrings', null, true),
  ('lats', 'Lats', null, true),
  ('quadriceps', 'Quadriceps', null, true),
  ('rear-delts', 'Rear Delts', null, true),
  ('side-delts', 'Side Delts', null, true),
  ('spinal-erectors', 'Spinal Erectors', null, true),
  ('traps', 'Traps', null, true),
  ('triceps', 'Triceps', null, true),
  ('upper-back', 'Upper Back', null, true)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  is_active = excluded.is_active;

insert into public.equipment (slug, name, description, is_active)
values
  ('barbell', 'Barbell', null, true),
  ('bench', 'Bench', null, true),
  ('bodyweight', 'Bodyweight', null, true),
  ('cable', 'Cable', null, true),
  ('dip-station', 'Dip Station', null, true),
  ('dumbbell', 'Dumbbell', null, true),
  ('hack-squat', 'Hack Squat', null, true),
  ('leg-press', 'Leg Press', null, true),
  ('plate-loaded-machine', 'Plate-Loaded Machine', null, true),
  ('pull-up-station', 'Pull-Up Station', null, true),
  ('selectorized-machine', 'Selectorized Machine', null, true),
  ('smith-machine', 'Smith Machine', null, true)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  is_active = excluded.is_active;

insert into public.exercise_families (slug, name, description, is_active)
values
  ('anti-extension', 'Anti-Extension', null, true),
  ('anti-rotation', 'Anti-Rotation', null, true),
  ('calf-raise', 'Calf Raise', null, true),
  ('chest-isolation', 'Chest Isolation', null, true),
  ('elbow-extension', 'Elbow Extension', null, true),
  ('elbow-flexion', 'Elbow Flexion', null, true),
  ('hip-abduction', 'Hip Abduction', null, true),
  ('hip-adduction', 'Hip Adduction', null, true),
  ('hip-extension', 'Hip Extension', null, true),
  ('hip-flexion-core', 'Hip Flexion Core', null, true),
  ('hip-hinge', 'Hip Hinge', null, true),
  ('horizontal-press', 'Horizontal Press', null, true),
  ('horizontal-pull', 'Horizontal Pull', null, true),
  ('incline-press', 'Incline Press', null, true),
  ('knee-dominant-squat', 'Knee-Dominant Squat', null, true),
  ('knee-extension', 'Knee Extension', null, true),
  ('knee-flexion', 'Knee Flexion', null, true),
  ('lateral-core', 'Lateral Core', null, true),
  ('loaded-carry', 'Loaded Carry', null, true),
  ('rear-delt', 'Rear-Delt Work', null, true),
  ('scapular-elevation', 'Scapular Elevation', null, true),
  ('shoulder-abduction', 'Shoulder Abduction', null, true),
  ('shoulder-extension', 'Shoulder Extension', null, true),
  ('shoulder-flexion', 'Shoulder Flexion', null, true),
  ('trunk-flexion', 'Trunk Flexion', null, true),
  ('trunk-rotation', 'Trunk Rotation', null, true),
  ('unilateral-knee-dominant', 'Unilateral Knee-Dominant', null, true),
  ('vertical-press', 'Vertical Press', null, true),
  ('vertical-pull', 'Vertical Pull', null, true),
  ('wrist-extension', 'Wrist Extension', null, true),
  ('wrist-flexion', 'Wrist Flexion', null, true)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  is_active = excluded.is_active;

insert into public.exercises (
  exercise_family_id,
  slug,
  name,
  description,
  version,
  is_active
)
select
  exercise_families.id,
  source.slug,
  source.name,
  source.description,
  source.version,
  source.is_active
from (
  values
    ('anti-extension', 'ab-wheel-rollout', 'Ab Wheel Rollout', null, 1, true),
    ('elbow-flexion', 'alternating-dumbbell-curl', 'Alternating Dumbbell Curl', null, 1, true),
    ('vertical-pull', 'assisted-pull-up', 'Assisted Pull-Up', null, 1, true),
    ('hip-hinge', 'back-extension', 'Back Extension', null, 1, true),
    ('knee-dominant-squat', 'barbell-back-squat', 'Barbell Back Squat', null, 1, true),
    ('horizontal-press', 'barbell-bench-press', 'Barbell Bench Press', null, 1, true),
    ('horizontal-pull', 'barbell-bent-over-row', 'Barbell Bent-Over Row', null, 1, true),
    ('elbow-flexion', 'barbell-curl', 'Barbell Curl', null, 1, true),
    ('knee-dominant-squat', 'barbell-front-squat', 'Barbell Front Squat', null, 1, true),
    ('hip-hinge', 'barbell-good-morning', 'Barbell Good Morning', null, 1, true),
    ('hip-extension', 'barbell-hip-thrust', 'Barbell Hip Thrust', null, 1, true),
    ('vertical-press', 'barbell-overhead-press', 'Barbell Overhead Press', null, 1, true),
    ('elbow-flexion', 'barbell-preacher-curl', 'Barbell Preacher Curl', null, 1, true),
    ('elbow-flexion', 'barbell-reverse-curl', 'Barbell Reverse Curl', null, 1, true),
    ('hip-hinge', 'barbell-romanian-deadlift', 'Barbell Romanian Deadlift', null, 1, true),
    ('scapular-elevation', 'barbell-shrug', 'Barbell Shrug', null, 1, true),
    ('elbow-flexion', 'bayesian-cable-curl', 'Bayesian Cable Curl', null, 1, true),
    ('rear-delt', 'bent-over-dumbbell-rear-delt-raise', 'Bent-Over Dumbbell Rear-Delt Raise', null, 1, true),
    ('chest-isolation', 'cable-chest-fly', 'Cable Chest Fly', null, 1, true),
    ('rear-delt', 'cable-face-pull', 'Cable Face Pull', null, 1, true),
    ('shoulder-flexion', 'cable-front-raise', 'Cable Front Raise', null, 1, true),
    ('hip-extension', 'cable-glute-kickback', 'Cable Glute Kickback', null, 1, true),
    ('shoulder-abduction', 'cable-lateral-raise', 'Cable Lateral Raise', null, 1, true),
    ('knee-flexion', 'cable-leg-curl', 'Cable Leg Curl', null, 1, true),
    ('knee-extension', 'cable-leg-extension', 'Cable Leg Extension', null, 1, true),
    ('trunk-rotation', 'cable-lift', 'Cable Lift', null, 1, true),
    ('anti-rotation', 'cable-pallof-press', 'Cable Pallof Press', null, 1, true),
    ('hip-extension', 'cable-pull-through', 'Cable Pull-Through', null, 1, true),
    ('shoulder-extension', 'cable-pullover', 'Cable Pullover', null, 1, true),
    ('rear-delt', 'cable-rear-delt-fly', 'Cable Rear-Delt Fly', null, 1, true),
    ('elbow-flexion', 'cable-reverse-curl', 'Cable Reverse Curl', null, 1, true),
    ('scapular-elevation', 'cable-shrug', 'Cable Shrug', null, 1, true),
    ('elbow-extension', 'cable-triceps-pushdown', 'Cable Triceps Pushdown', null, 1, true),
    ('trunk-rotation', 'cable-wood-chop', 'Cable Wood Chop', null, 1, true),
    ('horizontal-press', 'chest-dip', 'Chest-Focused Dip', null, 1, true),
    ('horizontal-pull', 'chest-supported-dumbbell-row', 'Chest-Supported Dumbbell Row', null, 1, true),
    ('horizontal-pull', 'chest-supported-plate-loaded-row', 'Chest-Supported Plate-Loaded Row', null, 1, true),
    ('elbow-extension', 'close-grip-barbell-bench-press', 'Close-Grip Barbell Bench Press', null, 1, true),
    ('hip-hinge', 'conventional-barbell-deadlift', 'Conventional Barbell Deadlift', null, 1, true),
    ('elbow-extension', 'cross-body-cable-triceps-extension', 'Cross-Body Cable Triceps Extension', null, 1, true),
    ('anti-extension', 'dead-bug', 'Dead Bug', null, 1, true),
    ('trunk-flexion', 'decline-bench-crunch', 'Decline Bench Crunch', null, 1, true),
    ('horizontal-press', 'dumbbell-bench-press', 'Dumbbell Bench Press', null, 1, true),
    ('unilateral-knee-dominant', 'dumbbell-bulgarian-split-squat', 'Dumbbell Bulgarian Split Squat', null, 1, true),
    ('chest-isolation', 'dumbbell-chest-fly', 'Dumbbell Chest Fly', null, 1, true),
    ('elbow-flexion', 'dumbbell-concentration-curl', 'Dumbbell Concentration Curl', null, 1, true),
    ('loaded-carry', 'dumbbell-farmer-carry', 'Dumbbell Farmer Carry', null, 1, true),
    ('shoulder-flexion', 'dumbbell-front-raise', 'Dumbbell Front Raise', null, 1, true),
    ('knee-dominant-squat', 'dumbbell-goblet-squat', 'Dumbbell Goblet Squat', null, 1, true),
    ('elbow-flexion', 'dumbbell-hammer-curl', 'Dumbbell Hammer Curl', null, 1, true),
    ('hip-extension', 'dumbbell-hip-thrust', 'Dumbbell Hip Thrust', null, 1, true),
    ('shoulder-abduction', 'dumbbell-lateral-raise', 'Dumbbell Lateral Raise', null, 1, true),
    ('elbow-extension', 'dumbbell-overhead-triceps-extension', 'Dumbbell Overhead Triceps Extension', null, 1, true),
    ('shoulder-extension', 'dumbbell-pullover', 'Dumbbell Pullover', null, 1, true),
    ('unilateral-knee-dominant', 'dumbbell-reverse-lunge', 'Dumbbell Reverse Lunge', null, 1, true),
    ('wrist-extension', 'dumbbell-reverse-wrist-curl', 'Dumbbell Reverse Wrist Curl', null, 1, true),
    ('hip-hinge', 'dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift', null, 1, true),
    ('scapular-elevation', 'dumbbell-shrug', 'Dumbbell Shrug', null, 1, true),
    ('calf-raise', 'dumbbell-standing-calf-raise', 'Dumbbell Standing Calf Raise', null, 1, true),
    ('unilateral-knee-dominant', 'dumbbell-step-up', 'Dumbbell Step-Up', null, 1, true),
    ('elbow-extension', 'dumbbell-triceps-kickback', 'Dumbbell Triceps Kickback', null, 1, true),
    ('unilateral-knee-dominant', 'dumbbell-walking-lunge', 'Dumbbell Walking Lunge', null, 1, true),
    ('wrist-flexion', 'dumbbell-wrist-curl', 'Dumbbell Wrist Curl', null, 1, true),
    ('anti-extension', 'front-plank', 'Front Plank', null, 1, true),
    ('knee-dominant-squat', 'hack-squat', 'Hack Squat', null, 1, true),
    ('hip-flexion-core', 'hanging-knee-raise', 'Hanging Knee Raise', null, 1, true),
    ('hip-flexion-core', 'hanging-leg-raise', 'Hanging Leg Raise', null, 1, true),
    ('incline-press', 'incline-barbell-bench-press', 'Incline Barbell Bench Press', null, 1, true),
    ('incline-press', 'incline-dumbbell-bench-press', 'Incline Dumbbell Bench Press', null, 1, true),
    ('elbow-flexion', 'incline-dumbbell-curl', 'Incline Dumbbell Curl', null, 1, true),
    ('incline-press', 'incline-machine-chest-press', 'Incline Machine Chest Press', null, 1, true),
    ('incline-press', 'incline-smith-bench-press', 'Incline Smith Machine Bench Press', null, 1, true),
    ('horizontal-pull', 'inverted-row', 'Inverted Row', null, 1, true),
    ('trunk-flexion', 'kneeling-cable-crunch', 'Kneeling Cable Crunch', null, 1, true),
    ('vertical-press', 'landmine-press', 'Landmine Press', null, 1, true),
    ('vertical-pull', 'lat-pulldown', 'Lat Pulldown', null, 1, true),
    ('shoulder-abduction', 'leaning-cable-lateral-raise', 'Leaning Cable Lateral Raise', null, 1, true),
    ('knee-dominant-squat', 'leg-press', 'Leg Press', null, 1, true),
    ('calf-raise', 'leg-press-calf-raise', 'Leg Press Calf Raise', null, 1, true),
    ('elbow-extension', 'lying-barbell-triceps-extension', 'Lying Barbell Triceps Extension', null, 1, true),
    ('elbow-extension', 'lying-dumbbell-triceps-extension', 'Lying Dumbbell Triceps Extension', null, 1, true),
    ('knee-flexion', 'nordic-hamstring-curl', 'Nordic Hamstring Curl', null, 1, true),
    ('horizontal-pull', 'one-arm-dumbbell-row', 'One-Arm Dumbbell Row', null, 1, true),
    ('elbow-extension', 'overhead-cable-triceps-extension', 'Overhead Cable Triceps Extension', null, 1, true),
    ('chest-isolation', 'pec-deck-fly', 'Pec Deck Fly', null, 1, true),
    ('horizontal-press', 'plate-loaded-chest-press', 'Plate-Loaded Chest Press', null, 1, true),
    ('vertical-pull', 'plate-loaded-lat-pulldown', 'Plate-Loaded Lat Pulldown', null, 1, true),
    ('knee-dominant-squat', 'plate-loaded-pendulum-squat', 'Plate-Loaded Pendulum Squat', null, 1, true),
    ('horizontal-pull', 'plate-loaded-row', 'Plate-Loaded Row', null, 1, true),
    ('calf-raise', 'plate-loaded-seated-calf-raise', 'Plate-Loaded Seated Calf Raise', null, 1, true),
    ('vertical-press', 'plate-loaded-shoulder-press', 'Plate-Loaded Shoulder Press', null, 1, true),
    ('horizontal-pull', 'plate-loaded-t-bar-row', 'Plate-Loaded T-Bar Row', null, 1, true),
    ('vertical-pull', 'pull-up', 'Pull-Up', null, 1, true),
    ('horizontal-press', 'push-up', 'Push-Up', null, 1, true),
    ('rear-delt', 'reverse-pec-deck', 'Reverse Pec Deck', null, 1, true),
    ('elbow-flexion', 'rope-hammer-curl', 'Rope Hammer Curl', null, 1, true),
    ('horizontal-pull', 'seated-cable-row', 'Seated Cable Row', null, 1, true),
    ('vertical-press', 'seated-dumbbell-shoulder-press', 'Seated Dumbbell Shoulder Press', null, 1, true),
    ('trunk-flexion', 'selectorized-abdominal-crunch', 'Selectorized Abdominal Crunch', null, 1, true),
    ('horizontal-press', 'selectorized-chest-press', 'Selectorized Chest Press', null, 1, true),
    ('hip-extension', 'selectorized-glute-drive', 'Selectorized Glute Drive', null, 1, true),
    ('hip-abduction', 'selectorized-hip-abduction', 'Selectorized Hip Abduction', null, 1, true),
    ('hip-adduction', 'selectorized-hip-adduction', 'Selectorized Hip Adduction', null, 1, true),
    ('shoulder-abduction', 'selectorized-lateral-raise', 'Selectorized Lateral Raise', null, 1, true),
    ('knee-extension', 'selectorized-leg-extension', 'Selectorized Leg Extension', null, 1, true),
    ('knee-flexion', 'selectorized-lying-leg-curl', 'Selectorized Lying Leg Curl', null, 1, true),
    ('elbow-flexion', 'selectorized-preacher-curl', 'Selectorized Preacher Curl', null, 1, true),
    ('shoulder-extension', 'selectorized-pullover', 'Selectorized Pullover', null, 1, true),
    ('knee-flexion', 'selectorized-seated-leg-curl', 'Selectorized Seated Leg Curl', null, 1, true),
    ('horizontal-pull', 'selectorized-seated-row', 'Selectorized Seated Row', null, 1, true),
    ('vertical-press', 'selectorized-shoulder-press', 'Selectorized Shoulder Press', null, 1, true),
    ('calf-raise', 'selectorized-standing-calf-raise', 'Selectorized Standing Calf Raise', null, 1, true),
    ('elbow-extension', 'selectorized-triceps-extension', 'Selectorized Triceps Extension', null, 1, true),
    ('lateral-core', 'side-plank', 'Side Plank', null, 1, true),
    ('horizontal-press', 'single-arm-cable-chest-press', 'Single-Arm Cable Chest Press', null, 1, true),
    ('elbow-extension', 'single-arm-cable-pushdown', 'Single-Arm Cable Pushdown', null, 1, true),
    ('horizontal-pull', 'single-arm-cable-row', 'Single-Arm Cable Row', null, 1, true),
    ('vertical-press', 'single-arm-cable-shoulder-press', 'Single-Arm Cable Shoulder Press', null, 1, true),
    ('elbow-flexion', 'single-arm-dumbbell-preacher-curl', 'Single-Arm Dumbbell Preacher Curl', null, 1, true),
    ('vertical-pull', 'single-arm-lat-pulldown', 'Single-Arm Lat Pulldown', null, 1, true),
    ('knee-extension', 'single-leg-extension', 'Single-Leg Extension', null, 1, true),
    ('knee-flexion', 'single-leg-standing-curl', 'Single-Leg Standing Curl', null, 1, true),
    ('horizontal-press', 'smith-bench-press', 'Smith Machine Bench Press', null, 1, true),
    ('horizontal-pull', 'smith-bent-over-row', 'Smith Machine Bent-Over Row', null, 1, true),
    ('elbow-extension', 'smith-jm-press', 'Smith Machine JM Press', null, 1, true),
    ('calf-raise', 'smith-machine-calf-raise', 'Smith Machine Calf Raise', null, 1, true),
    ('hip-extension', 'smith-machine-hip-thrust', 'Smith Machine Hip Thrust', null, 1, true),
    ('vertical-press', 'smith-machine-overhead-press', 'Smith Machine Overhead Press', null, 1, true),
    ('hip-hinge', 'smith-machine-romanian-deadlift', 'Smith Machine Romanian Deadlift', null, 1, true),
    ('scapular-elevation', 'smith-machine-shrug', 'Smith Machine Shrug', null, 1, true),
    ('unilateral-knee-dominant', 'smith-machine-split-squat', 'Smith Machine Split Squat', null, 1, true),
    ('knee-dominant-squat', 'smith-machine-squat', 'Smith Machine Squat', null, 1, true),
    ('horizontal-press', 'standing-cable-chest-press', 'Standing Cable Chest Press', null, 1, true),
    ('elbow-flexion', 'standing-cable-curl', 'Standing Cable Curl', null, 1, true),
    ('hip-abduction', 'standing-cable-hip-abduction', 'Standing Cable Hip Abduction', null, 1, true),
    ('hip-adduction', 'standing-cable-hip-adduction', 'Standing Cable Hip Adduction', null, 1, true),
    ('vertical-press', 'standing-dumbbell-shoulder-press', 'Standing Dumbbell Shoulder Press', null, 1, true),
    ('hip-hinge', 'sumo-barbell-deadlift', 'Sumo Barbell Deadlift', null, 1, true),
    ('elbow-extension', 'triceps-dip', 'Triceps-Focused Dip', null, 1, true),
    ('horizontal-pull', 'wide-grip-machine-row', 'Wide-Grip Machine Row', null, 1, true)
) as source(family_slug, slug, name, description, version, is_active)
join public.exercise_families on exercise_families.slug = source.family_slug
on conflict (slug) do update set
  exercise_family_id = excluded.exercise_family_id,
  name = excluded.name,
  description = excluded.description,
  version = excluded.version,
  is_active = excluded.is_active;

insert into public.exercise_muscles (exercise_id, muscle_id, role, contribution)
select exercises.id, muscles.id, source.role, source.contribution
from (
  values
    ('ab-wheel-rollout', 'abs', 'primary', 1),
    ('alternating-dumbbell-curl', 'biceps', 'primary', 1),
    ('alternating-dumbbell-curl', 'forearms', 'secondary', 0.3),
    ('assisted-pull-up', 'biceps', 'secondary', 0.5),
    ('assisted-pull-up', 'lats', 'primary', 1),
    ('assisted-pull-up', 'upper-back', 'secondary', 0.4),
    ('back-extension', 'glutes', 'secondary', 0.6),
    ('back-extension', 'hamstrings', 'secondary', 0.5),
    ('back-extension', 'spinal-erectors', 'primary', 1),
    ('barbell-back-squat', 'adductors', 'secondary', 0.4),
    ('barbell-back-squat', 'glutes', 'secondary', 0.7),
    ('barbell-back-squat', 'quadriceps', 'primary', 1),
    ('barbell-back-squat', 'spinal-erectors', 'secondary', 0.3),
    ('barbell-bench-press', 'chest', 'primary', 1),
    ('barbell-bench-press', 'front-delts', 'secondary', 0.4),
    ('barbell-bench-press', 'triceps', 'secondary', 0.5),
    ('barbell-bent-over-row', 'biceps', 'secondary', 0.4),
    ('barbell-bent-over-row', 'lats', 'secondary', 0.7),
    ('barbell-bent-over-row', 'spinal-erectors', 'secondary', 0.4),
    ('barbell-bent-over-row', 'upper-back', 'primary', 1),
    ('barbell-curl', 'biceps', 'primary', 1),
    ('barbell-curl', 'forearms', 'secondary', 0.3),
    ('barbell-front-squat', 'abs', 'secondary', 0.4),
    ('barbell-front-squat', 'glutes', 'secondary', 0.5),
    ('barbell-front-squat', 'quadriceps', 'primary', 1),
    ('barbell-good-morning', 'glutes', 'secondary', 0.7),
    ('barbell-good-morning', 'hamstrings', 'primary', 1),
    ('barbell-good-morning', 'spinal-erectors', 'secondary', 0.5),
    ('barbell-hip-thrust', 'glutes', 'primary', 1),
    ('barbell-hip-thrust', 'hamstrings', 'secondary', 0.4),
    ('barbell-overhead-press', 'front-delts', 'primary', 1),
    ('barbell-overhead-press', 'side-delts', 'secondary', 0.6),
    ('barbell-overhead-press', 'triceps', 'secondary', 0.5),
    ('barbell-preacher-curl', 'biceps', 'primary', 1),
    ('barbell-reverse-curl', 'biceps', 'secondary', 0.5),
    ('barbell-reverse-curl', 'forearms', 'primary', 1),
    ('barbell-romanian-deadlift', 'glutes', 'secondary', 0.8),
    ('barbell-romanian-deadlift', 'hamstrings', 'primary', 1),
    ('barbell-romanian-deadlift', 'spinal-erectors', 'secondary', 0.4),
    ('barbell-shrug', 'forearms', 'secondary', 0.3),
    ('barbell-shrug', 'traps', 'primary', 1),
    ('bayesian-cable-curl', 'biceps', 'primary', 1),
    ('bent-over-dumbbell-rear-delt-raise', 'rear-delts', 'primary', 1),
    ('bent-over-dumbbell-rear-delt-raise', 'upper-back', 'secondary', 0.4),
    ('cable-chest-fly', 'chest', 'primary', 1),
    ('cable-face-pull', 'rear-delts', 'primary', 1),
    ('cable-face-pull', 'traps', 'secondary', 0.3),
    ('cable-face-pull', 'upper-back', 'secondary', 0.5),
    ('cable-front-raise', 'front-delts', 'primary', 1),
    ('cable-glute-kickback', 'glutes', 'primary', 1),
    ('cable-lateral-raise', 'side-delts', 'primary', 1),
    ('cable-leg-curl', 'hamstrings', 'primary', 1),
    ('cable-leg-extension', 'quadriceps', 'primary', 1),
    ('cable-lift', 'abs', 'primary', 1),
    ('cable-pallof-press', 'abs', 'primary', 1),
    ('cable-pull-through', 'glutes', 'primary', 1),
    ('cable-pull-through', 'hamstrings', 'secondary', 0.6),
    ('cable-pullover', 'lats', 'primary', 1),
    ('cable-rear-delt-fly', 'rear-delts', 'primary', 1),
    ('cable-rear-delt-fly', 'upper-back', 'secondary', 0.4),
    ('cable-reverse-curl', 'biceps', 'secondary', 0.5),
    ('cable-reverse-curl', 'forearms', 'primary', 1),
    ('cable-shrug', 'forearms', 'secondary', 0.2),
    ('cable-shrug', 'traps', 'primary', 1),
    ('cable-triceps-pushdown', 'triceps', 'primary', 1),
    ('cable-wood-chop', 'abs', 'primary', 1),
    ('chest-dip', 'chest', 'primary', 1),
    ('chest-dip', 'front-delts', 'secondary', 0.3),
    ('chest-dip', 'triceps', 'secondary', 0.5),
    ('chest-supported-dumbbell-row', 'biceps', 'secondary', 0.4),
    ('chest-supported-dumbbell-row', 'lats', 'secondary', 0.6),
    ('chest-supported-dumbbell-row', 'upper-back', 'primary', 1),
    ('chest-supported-plate-loaded-row', 'biceps', 'secondary', 0.4),
    ('chest-supported-plate-loaded-row', 'lats', 'secondary', 0.7),
    ('chest-supported-plate-loaded-row', 'upper-back', 'primary', 1),
    ('close-grip-barbell-bench-press', 'chest', 'secondary', 0.6),
    ('close-grip-barbell-bench-press', 'front-delts', 'secondary', 0.3),
    ('close-grip-barbell-bench-press', 'triceps', 'primary', 1),
    ('conventional-barbell-deadlift', 'glutes', 'primary', 1),
    ('conventional-barbell-deadlift', 'hamstrings', 'secondary', 0.7),
    ('conventional-barbell-deadlift', 'spinal-erectors', 'secondary', 0.6),
    ('conventional-barbell-deadlift', 'traps', 'secondary', 0.3),
    ('cross-body-cable-triceps-extension', 'triceps', 'primary', 1),
    ('dead-bug', 'abs', 'primary', 1),
    ('decline-bench-crunch', 'abs', 'primary', 1),
    ('dumbbell-bench-press', 'chest', 'primary', 1),
    ('dumbbell-bench-press', 'front-delts', 'secondary', 0.4),
    ('dumbbell-bench-press', 'triceps', 'secondary', 0.4),
    ('dumbbell-bulgarian-split-squat', 'adductors', 'secondary', 0.3),
    ('dumbbell-bulgarian-split-squat', 'glutes', 'secondary', 0.7),
    ('dumbbell-bulgarian-split-squat', 'quadriceps', 'primary', 1),
    ('dumbbell-chest-fly', 'chest', 'primary', 1),
    ('dumbbell-concentration-curl', 'biceps', 'primary', 1),
    ('dumbbell-farmer-carry', 'abs', 'secondary', 0.4),
    ('dumbbell-farmer-carry', 'forearms', 'primary', 1),
    ('dumbbell-farmer-carry', 'traps', 'secondary', 0.6),
    ('dumbbell-front-raise', 'front-delts', 'primary', 1),
    ('dumbbell-goblet-squat', 'abs', 'secondary', 0.3),
    ('dumbbell-goblet-squat', 'glutes', 'secondary', 0.6),
    ('dumbbell-goblet-squat', 'quadriceps', 'primary', 1),
    ('dumbbell-hammer-curl', 'biceps', 'primary', 1),
    ('dumbbell-hammer-curl', 'forearms', 'secondary', 0.5),
    ('dumbbell-hip-thrust', 'glutes', 'primary', 1),
    ('dumbbell-hip-thrust', 'hamstrings', 'secondary', 0.4),
    ('dumbbell-lateral-raise', 'side-delts', 'primary', 1),
    ('dumbbell-overhead-triceps-extension', 'triceps', 'primary', 1),
    ('dumbbell-pullover', 'chest', 'secondary', 0.3),
    ('dumbbell-pullover', 'lats', 'primary', 1),
    ('dumbbell-reverse-lunge', 'adductors', 'secondary', 0.3),
    ('dumbbell-reverse-lunge', 'glutes', 'primary', 1),
    ('dumbbell-reverse-lunge', 'quadriceps', 'secondary', 0.7),
    ('dumbbell-reverse-wrist-curl', 'forearms', 'primary', 1),
    ('dumbbell-romanian-deadlift', 'glutes', 'secondary', 0.8),
    ('dumbbell-romanian-deadlift', 'hamstrings', 'primary', 1),
    ('dumbbell-romanian-deadlift', 'spinal-erectors', 'secondary', 0.3),
    ('dumbbell-shrug', 'forearms', 'secondary', 0.3),
    ('dumbbell-shrug', 'traps', 'primary', 1),
    ('dumbbell-standing-calf-raise', 'calves', 'primary', 1),
    ('dumbbell-step-up', 'glutes', 'primary', 1),
    ('dumbbell-step-up', 'quadriceps', 'secondary', 0.7),
    ('dumbbell-triceps-kickback', 'triceps', 'primary', 1),
    ('dumbbell-walking-lunge', 'adductors', 'secondary', 0.3),
    ('dumbbell-walking-lunge', 'glutes', 'secondary', 0.7),
    ('dumbbell-walking-lunge', 'quadriceps', 'primary', 1),
    ('dumbbell-wrist-curl', 'forearms', 'primary', 1),
    ('front-plank', 'abs', 'primary', 1),
    ('hack-squat', 'glutes', 'secondary', 0.5),
    ('hack-squat', 'quadriceps', 'primary', 1),
    ('hanging-knee-raise', 'abs', 'primary', 1),
    ('hanging-leg-raise', 'abs', 'primary', 1),
    ('incline-barbell-bench-press', 'chest', 'primary', 1),
    ('incline-barbell-bench-press', 'front-delts', 'secondary', 0.6),
    ('incline-barbell-bench-press', 'triceps', 'secondary', 0.4),
    ('incline-dumbbell-bench-press', 'chest', 'primary', 1),
    ('incline-dumbbell-bench-press', 'front-delts', 'secondary', 0.6),
    ('incline-dumbbell-bench-press', 'triceps', 'secondary', 0.4),
    ('incline-dumbbell-curl', 'biceps', 'primary', 1),
    ('incline-machine-chest-press', 'chest', 'primary', 1),
    ('incline-machine-chest-press', 'front-delts', 'secondary', 0.5),
    ('incline-machine-chest-press', 'triceps', 'secondary', 0.4),
    ('incline-smith-bench-press', 'chest', 'primary', 1),
    ('incline-smith-bench-press', 'front-delts', 'secondary', 0.6),
    ('incline-smith-bench-press', 'triceps', 'secondary', 0.4),
    ('inverted-row', 'biceps', 'secondary', 0.4),
    ('inverted-row', 'lats', 'secondary', 0.6),
    ('inverted-row', 'upper-back', 'primary', 1),
    ('kneeling-cable-crunch', 'abs', 'primary', 1),
    ('landmine-press', 'chest', 'secondary', 0.4),
    ('landmine-press', 'front-delts', 'primary', 1),
    ('landmine-press', 'triceps', 'secondary', 0.4),
    ('lat-pulldown', 'biceps', 'secondary', 0.5),
    ('lat-pulldown', 'lats', 'primary', 1),
    ('lat-pulldown', 'upper-back', 'secondary', 0.4),
    ('leaning-cable-lateral-raise', 'side-delts', 'primary', 1),
    ('leg-press', 'adductors', 'secondary', 0.3),
    ('leg-press', 'glutes', 'secondary', 0.6),
    ('leg-press', 'quadriceps', 'primary', 1),
    ('leg-press-calf-raise', 'calves', 'primary', 1),
    ('lying-barbell-triceps-extension', 'triceps', 'primary', 1),
    ('lying-dumbbell-triceps-extension', 'triceps', 'primary', 1),
    ('nordic-hamstring-curl', 'hamstrings', 'primary', 1),
    ('one-arm-dumbbell-row', 'biceps', 'secondary', 0.4),
    ('one-arm-dumbbell-row', 'lats', 'primary', 1),
    ('one-arm-dumbbell-row', 'upper-back', 'secondary', 0.6),
    ('overhead-cable-triceps-extension', 'triceps', 'primary', 1),
    ('pec-deck-fly', 'chest', 'primary', 1),
    ('plate-loaded-chest-press', 'chest', 'primary', 1),
    ('plate-loaded-chest-press', 'front-delts', 'secondary', 0.3),
    ('plate-loaded-chest-press', 'triceps', 'secondary', 0.4),
    ('plate-loaded-lat-pulldown', 'biceps', 'secondary', 0.5),
    ('plate-loaded-lat-pulldown', 'lats', 'primary', 1),
    ('plate-loaded-lat-pulldown', 'upper-back', 'secondary', 0.4),
    ('plate-loaded-pendulum-squat', 'glutes', 'secondary', 0.5),
    ('plate-loaded-pendulum-squat', 'quadriceps', 'primary', 1),
    ('plate-loaded-row', 'biceps', 'secondary', 0.4),
    ('plate-loaded-row', 'lats', 'secondary', 0.7),
    ('plate-loaded-row', 'upper-back', 'primary', 1),
    ('plate-loaded-seated-calf-raise', 'calves', 'primary', 1),
    ('plate-loaded-shoulder-press', 'front-delts', 'primary', 1),
    ('plate-loaded-shoulder-press', 'side-delts', 'secondary', 0.6),
    ('plate-loaded-shoulder-press', 'triceps', 'secondary', 0.5),
    ('plate-loaded-t-bar-row', 'biceps', 'secondary', 0.4),
    ('plate-loaded-t-bar-row', 'lats', 'secondary', 0.7),
    ('plate-loaded-t-bar-row', 'upper-back', 'primary', 1),
    ('pull-up', 'biceps', 'secondary', 0.5),
    ('pull-up', 'lats', 'primary', 1),
    ('pull-up', 'upper-back', 'secondary', 0.4),
    ('push-up', 'chest', 'primary', 1),
    ('push-up', 'front-delts', 'secondary', 0.3),
    ('push-up', 'triceps', 'secondary', 0.5),
    ('reverse-pec-deck', 'rear-delts', 'primary', 1),
    ('reverse-pec-deck', 'upper-back', 'secondary', 0.4),
    ('rope-hammer-curl', 'biceps', 'primary', 1),
    ('rope-hammer-curl', 'forearms', 'secondary', 0.5),
    ('seated-cable-row', 'biceps', 'secondary', 0.4),
    ('seated-cable-row', 'lats', 'secondary', 0.7),
    ('seated-cable-row', 'upper-back', 'primary', 1),
    ('seated-dumbbell-shoulder-press', 'front-delts', 'primary', 1),
    ('seated-dumbbell-shoulder-press', 'side-delts', 'secondary', 0.6),
    ('seated-dumbbell-shoulder-press', 'triceps', 'secondary', 0.5),
    ('selectorized-abdominal-crunch', 'abs', 'primary', 1),
    ('selectorized-chest-press', 'chest', 'primary', 1),
    ('selectorized-chest-press', 'front-delts', 'secondary', 0.3),
    ('selectorized-chest-press', 'triceps', 'secondary', 0.4),
    ('selectorized-glute-drive', 'glutes', 'primary', 1),
    ('selectorized-glute-drive', 'hamstrings', 'secondary', 0.4),
    ('selectorized-hip-abduction', 'abductors', 'primary', 1),
    ('selectorized-hip-abduction', 'glutes', 'secondary', 0.4),
    ('selectorized-hip-adduction', 'adductors', 'primary', 1),
    ('selectorized-lateral-raise', 'side-delts', 'primary', 1),
    ('selectorized-leg-extension', 'quadriceps', 'primary', 1),
    ('selectorized-lying-leg-curl', 'hamstrings', 'primary', 1),
    ('selectorized-preacher-curl', 'biceps', 'primary', 1),
    ('selectorized-pullover', 'lats', 'primary', 1),
    ('selectorized-seated-leg-curl', 'hamstrings', 'primary', 1),
    ('selectorized-seated-row', 'biceps', 'secondary', 0.4),
    ('selectorized-seated-row', 'lats', 'secondary', 0.7),
    ('selectorized-seated-row', 'upper-back', 'primary', 1),
    ('selectorized-shoulder-press', 'front-delts', 'primary', 1),
    ('selectorized-shoulder-press', 'side-delts', 'secondary', 0.6),
    ('selectorized-shoulder-press', 'triceps', 'secondary', 0.5),
    ('selectorized-standing-calf-raise', 'calves', 'primary', 1),
    ('selectorized-triceps-extension', 'triceps', 'primary', 1),
    ('side-plank', 'abs', 'primary', 1),
    ('single-arm-cable-chest-press', 'chest', 'primary', 1),
    ('single-arm-cable-chest-press', 'front-delts', 'secondary', 0.3),
    ('single-arm-cable-chest-press', 'triceps', 'secondary', 0.4),
    ('single-arm-cable-pushdown', 'triceps', 'primary', 1),
    ('single-arm-cable-row', 'biceps', 'secondary', 0.4),
    ('single-arm-cable-row', 'lats', 'primary', 1),
    ('single-arm-cable-row', 'upper-back', 'secondary', 0.6),
    ('single-arm-cable-shoulder-press', 'front-delts', 'primary', 1),
    ('single-arm-cable-shoulder-press', 'side-delts', 'secondary', 0.5),
    ('single-arm-cable-shoulder-press', 'triceps', 'secondary', 0.4),
    ('single-arm-dumbbell-preacher-curl', 'biceps', 'primary', 1),
    ('single-arm-lat-pulldown', 'biceps', 'secondary', 0.4),
    ('single-arm-lat-pulldown', 'lats', 'primary', 1),
    ('single-leg-extension', 'quadriceps', 'primary', 1),
    ('single-leg-standing-curl', 'hamstrings', 'primary', 1),
    ('smith-bench-press', 'chest', 'primary', 1),
    ('smith-bench-press', 'front-delts', 'secondary', 0.4),
    ('smith-bench-press', 'triceps', 'secondary', 0.5),
    ('smith-bent-over-row', 'biceps', 'secondary', 0.4),
    ('smith-bent-over-row', 'lats', 'secondary', 0.7),
    ('smith-bent-over-row', 'spinal-erectors', 'secondary', 0.3),
    ('smith-bent-over-row', 'upper-back', 'primary', 1),
    ('smith-jm-press', 'chest', 'secondary', 0.4),
    ('smith-jm-press', 'front-delts', 'secondary', 0.3),
    ('smith-jm-press', 'triceps', 'primary', 1),
    ('smith-machine-calf-raise', 'calves', 'primary', 1),
    ('smith-machine-hip-thrust', 'glutes', 'primary', 1),
    ('smith-machine-hip-thrust', 'hamstrings', 'secondary', 0.4),
    ('smith-machine-overhead-press', 'front-delts', 'primary', 1),
    ('smith-machine-overhead-press', 'side-delts', 'secondary', 0.6),
    ('smith-machine-overhead-press', 'triceps', 'secondary', 0.5),
    ('smith-machine-romanian-deadlift', 'glutes', 'secondary', 0.8),
    ('smith-machine-romanian-deadlift', 'hamstrings', 'primary', 1),
    ('smith-machine-romanian-deadlift', 'spinal-erectors', 'secondary', 0.3),
    ('smith-machine-shrug', 'forearms', 'secondary', 0.2),
    ('smith-machine-shrug', 'traps', 'primary', 1),
    ('smith-machine-split-squat', 'glutes', 'secondary', 0.7),
    ('smith-machine-split-squat', 'quadriceps', 'primary', 1),
    ('smith-machine-squat', 'glutes', 'secondary', 0.6),
    ('smith-machine-squat', 'quadriceps', 'primary', 1),
    ('standing-cable-chest-press', 'chest', 'primary', 1),
    ('standing-cable-chest-press', 'front-delts', 'secondary', 0.3),
    ('standing-cable-chest-press', 'triceps', 'secondary', 0.4),
    ('standing-cable-curl', 'biceps', 'primary', 1),
    ('standing-cable-hip-abduction', 'abductors', 'primary', 1),
    ('standing-cable-hip-abduction', 'glutes', 'secondary', 0.4),
    ('standing-cable-hip-adduction', 'adductors', 'primary', 1),
    ('standing-dumbbell-shoulder-press', 'front-delts', 'primary', 1),
    ('standing-dumbbell-shoulder-press', 'side-delts', 'secondary', 0.6),
    ('standing-dumbbell-shoulder-press', 'triceps', 'secondary', 0.5),
    ('sumo-barbell-deadlift', 'adductors', 'secondary', 0.7),
    ('sumo-barbell-deadlift', 'glutes', 'primary', 1),
    ('sumo-barbell-deadlift', 'hamstrings', 'secondary', 0.4),
    ('sumo-barbell-deadlift', 'quadriceps', 'secondary', 0.5),
    ('triceps-dip', 'chest', 'secondary', 0.5),
    ('triceps-dip', 'front-delts', 'secondary', 0.3),
    ('triceps-dip', 'triceps', 'primary', 1),
    ('wide-grip-machine-row', 'biceps', 'secondary', 0.3),
    ('wide-grip-machine-row', 'rear-delts', 'secondary', 0.5),
    ('wide-grip-machine-row', 'upper-back', 'primary', 1)
) as source(exercise_slug, muscle_slug, role, contribution)
join public.exercises on exercises.slug = source.exercise_slug
join public.muscles on muscles.slug = source.muscle_slug
on conflict (exercise_id, muscle_id) do update set
  role = excluded.role,
  contribution = excluded.contribution;

insert into public.exercise_equipment (exercise_id, equipment_id, requirement)
select exercises.id, equipment.id, source.requirement
from (
  values
    ('ab-wheel-rollout', 'bodyweight', 'required'),
    ('alternating-dumbbell-curl', 'dumbbell', 'required'),
    ('assisted-pull-up', 'pull-up-station', 'required'),
    ('assisted-pull-up', 'selectorized-machine', 'required'),
    ('back-extension', 'bench', 'required'),
    ('back-extension', 'bodyweight', 'required'),
    ('barbell-back-squat', 'barbell', 'required'),
    ('barbell-bench-press', 'barbell', 'required'),
    ('barbell-bench-press', 'bench', 'required'),
    ('barbell-bent-over-row', 'barbell', 'required'),
    ('barbell-curl', 'barbell', 'required'),
    ('barbell-front-squat', 'barbell', 'required'),
    ('barbell-good-morning', 'barbell', 'required'),
    ('barbell-hip-thrust', 'barbell', 'required'),
    ('barbell-hip-thrust', 'bench', 'required'),
    ('barbell-overhead-press', 'barbell', 'required'),
    ('barbell-preacher-curl', 'barbell', 'required'),
    ('barbell-preacher-curl', 'bench', 'required'),
    ('barbell-reverse-curl', 'barbell', 'required'),
    ('barbell-romanian-deadlift', 'barbell', 'required'),
    ('barbell-shrug', 'barbell', 'required'),
    ('bayesian-cable-curl', 'cable', 'required'),
    ('bent-over-dumbbell-rear-delt-raise', 'dumbbell', 'required'),
    ('cable-chest-fly', 'cable', 'required'),
    ('cable-face-pull', 'cable', 'required'),
    ('cable-front-raise', 'cable', 'required'),
    ('cable-glute-kickback', 'cable', 'required'),
    ('cable-lateral-raise', 'cable', 'required'),
    ('cable-leg-curl', 'cable', 'required'),
    ('cable-leg-extension', 'cable', 'required'),
    ('cable-lift', 'cable', 'required'),
    ('cable-pallof-press', 'cable', 'required'),
    ('cable-pull-through', 'cable', 'required'),
    ('cable-pullover', 'cable', 'required'),
    ('cable-rear-delt-fly', 'cable', 'required'),
    ('cable-reverse-curl', 'cable', 'required'),
    ('cable-shrug', 'cable', 'required'),
    ('cable-triceps-pushdown', 'cable', 'required'),
    ('cable-wood-chop', 'cable', 'required'),
    ('chest-dip', 'bodyweight', 'required'),
    ('chest-dip', 'dip-station', 'required'),
    ('chest-supported-dumbbell-row', 'bench', 'required'),
    ('chest-supported-dumbbell-row', 'dumbbell', 'required'),
    ('chest-supported-plate-loaded-row', 'plate-loaded-machine', 'required'),
    ('close-grip-barbell-bench-press', 'barbell', 'required'),
    ('close-grip-barbell-bench-press', 'bench', 'required'),
    ('conventional-barbell-deadlift', 'barbell', 'required'),
    ('cross-body-cable-triceps-extension', 'cable', 'required'),
    ('dead-bug', 'bodyweight', 'required'),
    ('decline-bench-crunch', 'bench', 'required'),
    ('decline-bench-crunch', 'bodyweight', 'required'),
    ('dumbbell-bench-press', 'bench', 'required'),
    ('dumbbell-bench-press', 'dumbbell', 'required'),
    ('dumbbell-bulgarian-split-squat', 'bench', 'required'),
    ('dumbbell-bulgarian-split-squat', 'dumbbell', 'required'),
    ('dumbbell-chest-fly', 'bench', 'required'),
    ('dumbbell-chest-fly', 'dumbbell', 'required'),
    ('dumbbell-concentration-curl', 'dumbbell', 'required'),
    ('dumbbell-farmer-carry', 'dumbbell', 'required'),
    ('dumbbell-front-raise', 'dumbbell', 'required'),
    ('dumbbell-goblet-squat', 'dumbbell', 'required'),
    ('dumbbell-hammer-curl', 'dumbbell', 'required'),
    ('dumbbell-hip-thrust', 'bench', 'required'),
    ('dumbbell-hip-thrust', 'dumbbell', 'required'),
    ('dumbbell-lateral-raise', 'dumbbell', 'required'),
    ('dumbbell-overhead-triceps-extension', 'dumbbell', 'required'),
    ('dumbbell-pullover', 'bench', 'required'),
    ('dumbbell-pullover', 'dumbbell', 'required'),
    ('dumbbell-reverse-lunge', 'dumbbell', 'required'),
    ('dumbbell-reverse-wrist-curl', 'bench', 'required'),
    ('dumbbell-reverse-wrist-curl', 'dumbbell', 'required'),
    ('dumbbell-romanian-deadlift', 'dumbbell', 'required'),
    ('dumbbell-shrug', 'dumbbell', 'required'),
    ('dumbbell-standing-calf-raise', 'dumbbell', 'required'),
    ('dumbbell-step-up', 'bench', 'required'),
    ('dumbbell-step-up', 'dumbbell', 'required'),
    ('dumbbell-triceps-kickback', 'dumbbell', 'required'),
    ('dumbbell-walking-lunge', 'dumbbell', 'required'),
    ('dumbbell-wrist-curl', 'bench', 'required'),
    ('dumbbell-wrist-curl', 'dumbbell', 'required'),
    ('front-plank', 'bodyweight', 'required'),
    ('hack-squat', 'hack-squat', 'required'),
    ('hanging-knee-raise', 'bodyweight', 'required'),
    ('hanging-knee-raise', 'pull-up-station', 'required'),
    ('hanging-leg-raise', 'bodyweight', 'required'),
    ('hanging-leg-raise', 'pull-up-station', 'required'),
    ('incline-barbell-bench-press', 'barbell', 'required'),
    ('incline-barbell-bench-press', 'bench', 'required'),
    ('incline-dumbbell-bench-press', 'bench', 'required'),
    ('incline-dumbbell-bench-press', 'dumbbell', 'required'),
    ('incline-dumbbell-curl', 'bench', 'required'),
    ('incline-dumbbell-curl', 'dumbbell', 'required'),
    ('incline-machine-chest-press', 'plate-loaded-machine', 'required'),
    ('incline-smith-bench-press', 'bench', 'required'),
    ('incline-smith-bench-press', 'smith-machine', 'required'),
    ('inverted-row', 'bodyweight', 'required'),
    ('inverted-row', 'smith-machine', 'required'),
    ('kneeling-cable-crunch', 'cable', 'required'),
    ('landmine-press', 'barbell', 'required'),
    ('lat-pulldown', 'cable', 'required'),
    ('leaning-cable-lateral-raise', 'cable', 'required'),
    ('leg-press', 'leg-press', 'required'),
    ('leg-press-calf-raise', 'leg-press', 'required'),
    ('lying-barbell-triceps-extension', 'barbell', 'required'),
    ('lying-barbell-triceps-extension', 'bench', 'required'),
    ('lying-dumbbell-triceps-extension', 'bench', 'required'),
    ('lying-dumbbell-triceps-extension', 'dumbbell', 'required'),
    ('nordic-hamstring-curl', 'bench', 'required'),
    ('nordic-hamstring-curl', 'bodyweight', 'required'),
    ('one-arm-dumbbell-row', 'bench', 'required'),
    ('one-arm-dumbbell-row', 'dumbbell', 'required'),
    ('overhead-cable-triceps-extension', 'cable', 'required'),
    ('pec-deck-fly', 'selectorized-machine', 'required'),
    ('plate-loaded-chest-press', 'plate-loaded-machine', 'required'),
    ('plate-loaded-lat-pulldown', 'plate-loaded-machine', 'required'),
    ('plate-loaded-pendulum-squat', 'plate-loaded-machine', 'required'),
    ('plate-loaded-row', 'plate-loaded-machine', 'required'),
    ('plate-loaded-seated-calf-raise', 'plate-loaded-machine', 'required'),
    ('plate-loaded-shoulder-press', 'plate-loaded-machine', 'required'),
    ('plate-loaded-t-bar-row', 'plate-loaded-machine', 'required'),
    ('pull-up', 'bodyweight', 'required'),
    ('pull-up', 'pull-up-station', 'required'),
    ('push-up', 'bodyweight', 'required'),
    ('reverse-pec-deck', 'selectorized-machine', 'required'),
    ('rope-hammer-curl', 'cable', 'required'),
    ('seated-cable-row', 'cable', 'required'),
    ('seated-dumbbell-shoulder-press', 'bench', 'required'),
    ('seated-dumbbell-shoulder-press', 'dumbbell', 'required'),
    ('selectorized-abdominal-crunch', 'selectorized-machine', 'required'),
    ('selectorized-chest-press', 'selectorized-machine', 'required'),
    ('selectorized-glute-drive', 'selectorized-machine', 'required'),
    ('selectorized-hip-abduction', 'selectorized-machine', 'required'),
    ('selectorized-hip-adduction', 'selectorized-machine', 'required'),
    ('selectorized-lateral-raise', 'selectorized-machine', 'required'),
    ('selectorized-leg-extension', 'selectorized-machine', 'required'),
    ('selectorized-lying-leg-curl', 'selectorized-machine', 'required'),
    ('selectorized-preacher-curl', 'selectorized-machine', 'required'),
    ('selectorized-pullover', 'selectorized-machine', 'required'),
    ('selectorized-seated-leg-curl', 'selectorized-machine', 'required'),
    ('selectorized-seated-row', 'selectorized-machine', 'required'),
    ('selectorized-shoulder-press', 'selectorized-machine', 'required'),
    ('selectorized-standing-calf-raise', 'selectorized-machine', 'required'),
    ('selectorized-triceps-extension', 'selectorized-machine', 'required'),
    ('side-plank', 'bodyweight', 'required'),
    ('single-arm-cable-chest-press', 'cable', 'required'),
    ('single-arm-cable-pushdown', 'cable', 'required'),
    ('single-arm-cable-row', 'cable', 'required'),
    ('single-arm-cable-shoulder-press', 'cable', 'required'),
    ('single-arm-dumbbell-preacher-curl', 'bench', 'required'),
    ('single-arm-dumbbell-preacher-curl', 'dumbbell', 'required'),
    ('single-arm-lat-pulldown', 'cable', 'required'),
    ('single-leg-extension', 'selectorized-machine', 'required'),
    ('single-leg-standing-curl', 'selectorized-machine', 'required'),
    ('smith-bench-press', 'bench', 'required'),
    ('smith-bench-press', 'smith-machine', 'required'),
    ('smith-bent-over-row', 'smith-machine', 'required'),
    ('smith-jm-press', 'bench', 'required'),
    ('smith-jm-press', 'smith-machine', 'required'),
    ('smith-machine-calf-raise', 'smith-machine', 'required'),
    ('smith-machine-hip-thrust', 'bench', 'required'),
    ('smith-machine-hip-thrust', 'smith-machine', 'required'),
    ('smith-machine-overhead-press', 'bench', 'required'),
    ('smith-machine-overhead-press', 'smith-machine', 'required'),
    ('smith-machine-romanian-deadlift', 'smith-machine', 'required'),
    ('smith-machine-shrug', 'smith-machine', 'required'),
    ('smith-machine-split-squat', 'smith-machine', 'required'),
    ('smith-machine-squat', 'smith-machine', 'required'),
    ('standing-cable-chest-press', 'cable', 'required'),
    ('standing-cable-curl', 'cable', 'required'),
    ('standing-cable-hip-abduction', 'cable', 'required'),
    ('standing-cable-hip-adduction', 'cable', 'required'),
    ('standing-dumbbell-shoulder-press', 'dumbbell', 'required'),
    ('sumo-barbell-deadlift', 'barbell', 'required'),
    ('triceps-dip', 'bodyweight', 'required'),
    ('triceps-dip', 'dip-station', 'required'),
    ('wide-grip-machine-row', 'selectorized-machine', 'required')
) as source(exercise_slug, equipment_slug, requirement)
join public.exercises on exercises.slug = source.exercise_slug
join public.equipment on equipment.slug = source.equipment_slug
on conflict (exercise_id, equipment_id) do update set
  requirement = excluded.requirement;

insert into public.exercise_substitutions (
  source_exercise_id,
  substitute_exercise_id,
  reason_code,
  compatibility_score,
  notes,
  is_active
)
select
  source_exercise.id,
  substitute_exercise.id,
  source.reason_code,
  source.compatibility_score,
  source.notes,
  source.is_active
from (
  values
    ('barbell-back-squat', 'dumbbell-goblet-squat', 'barbell_unavailable', 0.78, null, true),
    ('barbell-back-squat', 'leg-press', 'squat_station_unavailable', 0.76, null, true),
    ('barbell-back-squat', 'smith-machine-squat', 'rack_unavailable', 0.9, null, true),
    ('barbell-bench-press', 'dumbbell-bench-press', 'barbell_unavailable', 0.92, null, true),
    ('barbell-bench-press', 'plate-loaded-chest-press', 'bench_station_unavailable', 0.84, null, true),
    ('barbell-bench-press', 'smith-bench-press', 'free_weight_station_unavailable', 0.9, null, true),
    ('barbell-bent-over-row', 'chest-supported-dumbbell-row', 'supported_row_preferred', 0.8, null, true),
    ('barbell-bent-over-row', 'one-arm-dumbbell-row', 'barbell_unavailable', 0.85, null, true),
    ('barbell-bent-over-row', 'smith-bent-over-row', 'free_weight_station_unavailable', 0.9, null, true),
    ('barbell-curl', 'alternating-dumbbell-curl', 'barbell_unavailable', 0.88, null, true),
    ('barbell-curl', 'standing-cable-curl', 'free_weights_unavailable', 0.86, null, true),
    ('barbell-hip-thrust', 'dumbbell-hip-thrust', 'barbell_unavailable', 0.84, null, true),
    ('barbell-hip-thrust', 'smith-machine-hip-thrust', 'barbell_station_unavailable', 0.92, null, true),
    ('barbell-overhead-press', 'smith-machine-overhead-press', 'free_weight_station_unavailable', 0.88, null, true),
    ('barbell-overhead-press', 'standing-dumbbell-shoulder-press', 'barbell_unavailable', 0.9, null, true),
    ('barbell-romanian-deadlift', 'dumbbell-romanian-deadlift', 'barbell_unavailable', 0.92, null, true),
    ('barbell-romanian-deadlift', 'smith-machine-romanian-deadlift', 'free_weight_station_unavailable', 0.9, null, true),
    ('cable-triceps-pushdown', 'selectorized-triceps-extension', 'cable_station_unavailable', 0.82, null, true),
    ('cable-triceps-pushdown', 'single-arm-cable-pushdown', 'attachment_unavailable', 0.92, null, true),
    ('dumbbell-bench-press', 'barbell-bench-press', 'dumbbells_unavailable', 0.9, null, true),
    ('dumbbell-bench-press', 'selectorized-chest-press', 'bench_unavailable', 0.82, null, true),
    ('dumbbell-lateral-raise', 'cable-lateral-raise', 'dumbbells_unavailable', 0.9, null, true),
    ('dumbbell-lateral-raise', 'selectorized-lateral-raise', 'free_weights_unavailable', 0.86, null, true),
    ('dumbbell-romanian-deadlift', 'cable-pull-through', 'dumbbells_unavailable', 0.74, null, true),
    ('hack-squat', 'leg-press', 'hack_squat_unavailable', 0.88, null, true),
    ('hack-squat', 'plate-loaded-pendulum-squat', 'hack_squat_unavailable', 0.84, null, true),
    ('incline-barbell-bench-press', 'incline-dumbbell-bench-press', 'barbell_unavailable', 0.92, null, true),
    ('incline-barbell-bench-press', 'incline-smith-bench-press', 'free_weight_station_unavailable', 0.9, null, true),
    ('incline-dumbbell-bench-press', 'incline-machine-chest-press', 'bench_unavailable', 0.84, null, true),
    ('lat-pulldown', 'plate-loaded-lat-pulldown', 'cable_station_unavailable', 0.9, null, true),
    ('lat-pulldown', 'pull-up', 'cable_station_unavailable', 0.86, null, true),
    ('leg-press', 'hack-squat', 'leg_press_unavailable', 0.88, null, true),
    ('leg-press', 'smith-machine-squat', 'leg_press_unavailable', 0.78, null, true),
    ('overhead-cable-triceps-extension', 'dumbbell-overhead-triceps-extension', 'cable_station_unavailable', 0.88, null, true),
    ('pec-deck-fly', 'cable-chest-fly', 'pec_deck_unavailable', 0.9, null, true),
    ('pull-up', 'assisted-pull-up', 'assistance_required', 0.9, null, true),
    ('pull-up', 'lat-pulldown', 'pull_up_station_unavailable', 0.86, null, true),
    ('reverse-pec-deck', 'cable-rear-delt-fly', 'reverse_fly_machine_unavailable', 0.9, null, true),
    ('seated-cable-row', 'plate-loaded-row', 'cable_station_unavailable', 0.86, null, true),
    ('seated-cable-row', 'selectorized-seated-row', 'cable_station_unavailable', 0.9, null, true),
    ('seated-dumbbell-shoulder-press', 'selectorized-shoulder-press', 'dumbbells_unavailable', 0.86, null, true),
    ('selectorized-lateral-raise', 'cable-lateral-raise', 'lateral_raise_machine_unavailable', 0.9, null, true),
    ('selectorized-leg-extension', 'cable-leg-extension', 'leg_extension_unavailable', 0.78, null, true),
    ('selectorized-leg-extension', 'single-leg-extension', 'bilateral_setup_unavailable', 0.94, null, true),
    ('selectorized-preacher-curl', 'single-arm-dumbbell-preacher-curl', 'curl_machine_unavailable', 0.86, null, true),
    ('selectorized-seated-leg-curl', 'cable-leg-curl', 'leg_curl_machine_unavailable', 0.76, null, true),
    ('selectorized-seated-leg-curl', 'selectorized-lying-leg-curl', 'seated_curl_unavailable', 0.9, null, true),
    ('selectorized-seated-row', 'single-arm-cable-row', 'row_machine_unavailable', 0.82, null, true),
    ('smith-machine-hip-thrust', 'selectorized-glute-drive', 'smith_station_unavailable', 0.88, null, true),
    ('smith-machine-overhead-press', 'plate-loaded-shoulder-press', 'smith_station_unavailable', 0.84, null, true)
) as source(
  source_exercise_slug,
  substitute_exercise_slug,
  reason_code,
  compatibility_score,
  notes,
  is_active
)
join public.exercises as source_exercise
  on source_exercise.slug = source.source_exercise_slug
join public.exercises as substitute_exercise
  on substitute_exercise.slug = source.substitute_exercise_slug
on conflict (source_exercise_id, substitute_exercise_id) do update set
  reason_code = excluded.reason_code,
  compatibility_score = excluded.compatibility_score,
  notes = excluded.notes,
  is_active = excluded.is_active;

